// Star Shard — generated station corpus for the browser (0-indexed).
// Generated by tools/build-mansions.mjs from research/mansions-*.md +
// mansions-table.json — regenerate, never hand-edit (see OWNERSHIP.md).
//
// `station` is 0-27 (sigil.js/deck.js's convention), NOT the 1-28 `id`
// the permalink generator uses internally for itself.

export const STATIONS = [
  {
    "station": 0,
    "epithet": "The Gate",
    "slug": "the-gate",
    "kanji": "婁宿",
    "position": "0°00′ Aries – 12°51′ Aries",
    "stars": "β, γ Ari (Sheratan)",
    "match": "STRONG",
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Sharaṭān",
        "meaning": "\"the Two Signs / Horns\" — the marks that open the year"
      },
      {
        "sky": "India",
        "name": "Ashvinī",
        "meaning": "the twin horsemen — the gods' healers, first on every scene"
      },
      {
        "sky": "China",
        "name": "婁 Lóu",
        "meaning": "White Tiger quadrant · animal: dog"
      },
      {
        "sky": "Japan",
        "name": "婁宿",
        "meaning": "(grimoire: FY warrior Tatara, Byakko)"
      }
    ],
    "electionLore": "beginnings and journeys; the old books admit it's lousy for weddings. Picatrix: safe travel and return; also discord (hostile flag — history shelf only).",
    "birthEntry": "your mansion is The Gate — station one of twenty-eight, where the whole wheel begins. arabia saw two bright horns marking the year's opening; india saw twin horsemen here, the sky's first responders, always earliest on the scene. first-one-through energy: you're the friend who says \"ok, here's the plan\" while everyone else is still putting on shoes. beginnings aren't scary to you. they're home terrain ✦",
    "dailyCrossing": "the moon stands at The Gate tonight — station one, where the wheel restarts. tradition calls it good for beginnings and journeys. whatever you've been circling: start it ✦",
    "tags": [
      "beginnings",
      "travel",
      "initiative",
      "fresh-starts"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "dog",
    "guardianSky": "White Tiger (West/Autumn)",
    "hunger": {
      "deity": "Aśvins",
      "symbol": "horse's head"
    },
    "signSpan": "0°00' Ari – 12°51' Ari"
  },
  {
    "station": 1,
    "epithet": "The Bearer",
    "slug": "the-bearer",
    "kanji": "胃宿",
    "position": "12°51′ Aries – 25°43′ Aries",
    "stars": "ε, δ, ρ Ari (Botein)",
    "match": "PARTIAL",
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Buṭayn",
        "meaning": "\"the Little Belly (of the Ram)\" — where soft things are kept"
      },
      {
        "sky": "India",
        "name": "Bharaṇī",
        "meaning": "\"she who bears\" — deity Yama, keeper of thresholds"
      },
      {
        "sky": "China",
        "name": "胃 Wèi",
        "meaning": "\"the Stomach\" · White Tiger · animal: pheasant"
      },
      {
        "sky": "Japan",
        "name": "胃宿",
        "meaning": ""
      }
    ],
    "electionLore": "trade, and the finding of treasure. Picatrix: treasure-finding; holding captives (hostile flag).",
    "birthEntry": "your mansion is The Bearer — the station that holds and carries. arabia saw the ram's soft belly, the place where treasure hides; india named it for the one who bears — carrying something precious until it's ready to arrive. you're the friend who holds everyone's bags at the show, and their secrets after. what you keep, keeps. treasure-keeper energy ♡",
    "dailyCrossing": "the moon is with The Bearer tonight — a holding day. tradition calls it good for trade and for finding what's hidden. carry the thing carefully. check the pocket you forgot ✦",
    "tags": [
      "keeping",
      "trade",
      "patience",
      "hidden-treasure"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "pheasant",
    "guardianSky": "White Tiger (West/Autumn)",
    "hunger": {
      "deity": "Yama",
      "symbol": "yoni"
    },
    "signSpan": "12°51' Ari – 25°43' Ari"
  },
  {
    "station": 2,
    "epithet": "The Gathered Stars",
    "slug": "the-gathered-stars",
    "kanji": "昴宿",
    "position": "25°43′ Aries – 8°34′ Tau",
    "stars": "the Pleiades (M45) · determinant Alcyone (η Tau)",
    "match": "STRONG",
    "crossCultural": [
      {
        "sky": "Japan",
        "name": "昴宿 (Subaru)",
        "meaning": "the gathered stars — the everyday Japanese word for the Pleiades to this day; count the stars in the car logo ♡"
      },
      {
        "sky": "Arabia",
        "name": "al-Thurayyā",
        "meaning": "\"the many little ones\"; root linked to tharwa, abundance. So famous that al-Najm — \"the Star,\" no qualifier — meant this one"
      },
      {
        "sky": "India",
        "name": "Kṛttikā",
        "meaning": "deity Agni (fire) · symbol: blade/flame"
      },
      {
        "sky": "China",
        "name": "昴 Mǎo",
        "meaning": "White Tiger of the West · animal: rooster"
      }
    ],
    "electionLore": "Good for trade and marriage (al-Bīrūnī lineage). Agrippa, 1533: \"profitable to sailors, huntsmen, and alchemists.\" Picatrix: safe sailing, fire-work, married love.",
    "birthEntry": "your mansion is 昴宿 — Subaru. yes, that subaru: the gathered stars, the little heap of lights so famous that in japan it's just the name for the Pleiades, and in old arabic you could say \"the Star\" and everyone knew. six-or-seven lights that read as one shine — found-family energy, the friend group that moves like a single constellation. whole calendars watched you to know when summer starts. no pressure ♡",
    "dailyCrossing": "the moon is in 昴宿 tonight — Subaru, the gathered stars. a gathering day: tradition calls it good for making, trading, and starting things with friends. little lights, together, read as one ✦",
    "tags": [
      "making",
      "friends",
      "trade",
      "beginnings"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "rooster",
    "guardianSky": "White Tiger (West/Autumn)",
    "hunger": {
      "deity": "Agni",
      "symbol": "knife/flame"
    },
    "signSpan": "25°43' Ari – 8°34' Tau"
  },
  {
    "station": 3,
    "epithet": "The Follower",
    "slug": "the-follower",
    "kanji": "畢宿",
    "position": "8°34′ Taurus – 21°26′ Taurus",
    "stars": "Aldebaran + the Hyades",
    "match": "STRONG",
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Dabarān",
        "meaning": "\"the Follower\" — forever walking behind the Pleiades"
      },
      {
        "sky": "India",
        "name": "Rohiṇī",
        "meaning": "deity Brahmā · symbol: the chariot"
      },
      {
        "sky": "China",
        "name": "畢 Bì",
        "meaning": "\"the Net\" · White Tiger · animal: crow"
      },
      {
        "sky": "Japan",
        "name": "畢宿",
        "meaning": "(grimoire: FY warrior Amefuri)"
      }
    ],
    "electionLore": "good for building; bad for marriage (the poets' irony: the eternal suitor never weds). Picatrix: destruction and discord (hostile flag — history shelf only).",
    "birthEntry": "your mansion is The Follower — Aldebaran, the bright red eye that has walked the sky behind The Gathered Stars since forever. the desert poets told it as devotion: the one who follows what they love and never once loses sight of it. that's you. you don't chase trends — you keep faith. with your people, your obsessions, your decade-long fandoms. loyalty is your superpower, and the sky has been demonstrating yours nightly for a few thousand years ✦",
    "dailyCrossing": "the moon rides with The Follower tonight — Aldebaran, trailing its beloved Pleiades like always. a loyalty day: good for building, tradition says, and for staying on the trail of what you love ♡",
    "tags": [
      "loyalty",
      "building",
      "devotion",
      "focus"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "crow",
    "guardianSky": "White Tiger (West/Autumn)",
    "hunger": {
      "deity": "Brahmā",
      "symbol": "chariot"
    },
    "signSpan": "8°34' Tau – 21°26' Tau"
  },
  {
    "station": 4,
    "epithet": "The Blaze",
    "slug": "the-blaze",
    "kanji": "觜宿",
    "position": "21°26′ Taurus – 4°17′ Gemini",
    "stars": "λ, φ¹, φ² Ori (Orion's head)",
    "match": "STRONG",
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Haqʿa",
        "meaning": "\"the White Spot\" — a horse's star-blaze, on Orion's brow"
      },
      {
        "sky": "India",
        "name": "Mṛgaśīrṣā",
        "meaning": "\"the deer's head\" — gentle, quick, curious"
      },
      {
        "sky": "China",
        "name": "觜 Zī",
        "meaning": "\"the Beak\" · White Tiger · animal: monkey"
      },
      {
        "sky": "Japan",
        "name": "觜宿",
        "meaning": "(grimoire: FY warrior Toroki)"
      }
    ],
    "electionLore": "travel, learning, and safe returns from journeys. Picatrix: safe journeys, teaching, health — one of the gentle stations even on the history shelf.",
    "birthEntry": "your mansion is The Blaze — the small white star-mark on the forehead of the sky, right on orion's head. the old lists call it the station of travel and learning: the mark of the student who leaves, learns, and comes home glowing. india saw a deer's head here — curious, quick, impossible to catch until it decides to be caught. you collect knowledge like souvenirs, and you always come back changed ✦",
    "dailyCrossing": "the moon is at The Blaze tonight — the little white mark of learning. tradition calls today good for studying, traveling, and coming home smarter than you left ✦",
    "tags": [
      "learning",
      "travel",
      "curiosity",
      "homecoming"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "monkey",
    "guardianSky": "White Tiger (West/Autumn)",
    "hunger": {
      "deity": "Soma, the moon-draught",
      "symbol": "deer's head"
    },
    "signSpan": "21°26' Tau – 4°17' Gem"
  },
  {
    "station": 5,
    "epithet": "The Storm",
    "slug": "the-storm",
    "kanji": "參宿",
    "position": "4°17′ Gemini – 17°09′ Gemini",
    "stars": "γ, ξ Gem (Alhena)",
    "match": null,
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Hanʿa",
        "meaning": "\"the Brand\" — the camel's neck-mark"
      },
      {
        "sky": "India",
        "name": "Ārdrā",
        "meaning": "\"the moist one\" — Betelgeuse, the storm god Rudra's star"
      },
      {
        "sky": "China",
        "name": "參 Shēn",
        "meaning": "Orion itself · White Tiger · animal: ape"
      },
      {
        "sky": "Japan",
        "name": "參宿",
        "meaning": "(grimoire: FY warrior Karasuki)"
      }
    ],
    "electionLore": "the fierce jobs — hunting, sieges, martial work. Picatrix: hunting, revenge, harming crops (hostile flags — firmly on the history shelf).",
    "birthEntry": "your mansion is The Storm — india's Ārdrā, the rain-bearing star of the storm god, burning in orion's shoulder. the old books gave this station the fierce jobs, and here's the honest read: that's not doom, it's voltage. storm-born people feel everything at full amplitude — and when you finally let it rain, you clear the air for everyone. after your weather passes, the whole sky is greener ✦",
    "dailyCrossing": "the moon crosses The Storm tonight. voltage day: big feelings, fast skies. the old calendars saved the fierce work for this station — spend the charge on something worth it, then let it rain ♡",
    "tags": [
      "intensity",
      "release",
      "courage",
      "clearing-the-air"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "ape",
    "guardianSky": "White Tiger (West/Autumn)",
    "hunger": {
      "deity": "Rudra, the howler in the storm",
      "symbol": "teardrop · a head"
    },
    "signSpan": "4°17' Gem – 17°09' Gem"
  },
  {
    "station": 6,
    "epithet": "The Return",
    "slug": "the-return",
    "kanji": "井宿",
    "position": "17°09′ Gemini – 0°00′ Cancer",
    "stars": "Castor & Pollux",
    "match": null,
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Dhirāʿ",
        "meaning": "\"the Forearm\" — reaching out"
      },
      {
        "sky": "India",
        "name": "Punarvasu",
        "meaning": "\"the light that returns\""
      },
      {
        "sky": "China",
        "name": "井 Jǐng",
        "meaning": "\"the Well\" · Vermilion Bird · animal: bian"
      },
      {
        "sky": "Japan",
        "name": "井宿",
        "meaning": "(grimoire: this mansion's FY warrior is Chichiri)"
      }
    ],
    "electionLore": "gain, friendship, lovers. Picatrix: trade, friendship, royal favor — gentle here too.",
    "birthEntry": "your mansion is The Return — castor and pollux, the twins, which india names Punarvasu: \"the light that comes back.\" this is the station of second chances and doors left open. friends who drift and find their way back to you. projects that revive the moment you touch them again. you're living proof that coming back counts as going forward ✦",
    "dailyCrossing": "the moon is at The Return tonight — the light that comes back. tradition calls today good for friendship, gain, and picking a thing back up. text them back. reopen the file ♡",
    "tags": [
      "friendship",
      "second-chances",
      "reunion",
      "gain"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "bian",
    "guardianSky": "Vermilion Bird (South/Summer)",
    "hunger": {
      "deity": "Aditi, the boundless mother",
      "symbol": "bow and quiver"
    },
    "signSpan": "17°09' Gem – 0°00' Cnc"
  },
  {
    "station": 7,
    "epithet": "The Ghost",
    "slug": "the-ghost",
    "kanji": "鬼宿",
    "position": "0°00′ Cancer – 12°51′ Cancer",
    "stars": "Praesepe (M44, the Beehive cluster) + γ, δ Cnc",
    "match": "STRONG",
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Nathra",
        "meaning": "\"the Nostril / gap\" — the Lion's muzzle-tuft of mist"
      },
      {
        "sky": "India",
        "name": "Puṣya",
        "meaning": "\"the nourisher\""
      },
      {
        "sky": "China",
        "name": "鬼 Guǐ",
        "meaning": "\"the Ghost\" — θ Cnc + the Praesepe haze · Vermilion Bird · animal: goat"
      },
      {
        "sky": "Japan",
        "name": "鬼宿",
        "meaning": "(grimoire: this is Tamahome's mansion — the protagonist of Fushigi Yūgi)"
      }
    ],
    "electionLore": "love, friendship, and the company of fellow travelers. Picatrix: love, friendship, safe travel — one of the gentlest stations even on the history shelf.",
    "birthEntry": "your mansion is The Ghost — and it's the least scary ghost in the sky. the \"ghost\" is a real little cloud of starlight: hundreds of tiny stars too soft to see one by one, so the old world saw a gentle haze and gave it the spookiest name possible. meanwhile the actual tradition here is love, friendship, and fellow travelers — india even calls this station the nourisher. that's you: quietly present, softly glowing, feeding everyone. the warmest possible haunting ♡",
    "dailyCrossing": "the moon drifts through The Ghost tonight — the soft haze of the beehive cluster. a gentle day: tradition calls it good for love, friendship, and the people who travel beside you. haunt someone kindly ✦",
    "tags": [
      "friendship",
      "love",
      "gentleness",
      "fellow-travelers"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "goat",
    "guardianSky": "Vermilion Bird (South/Summer)",
    "hunger": {
      "deity": "Bṛhaspati, priest of the gods",
      "symbol": "cow's udder · lotus"
    },
    "signSpan": "0°00' Cnc – 12°51' Cnc"
  },
  {
    "station": 8,
    "epithet": "The Glance",
    "slug": "the-glance",
    "kanji": "柳宿",
    "position": "12°51′ Cancer – 25°43′ Cancer",
    "stars": "κ Cnc + λ Leo",
    "match": "PARTIAL",
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Ṭarf",
        "meaning": "\"the Glance\" — the Lion's eye"
      },
      {
        "sky": "India",
        "name": "Āśleṣā",
        "meaning": "the serpent's embrace — Hydra's head"
      },
      {
        "sky": "China",
        "name": "柳 Liǔ",
        "meaning": "\"the Willow\" · Vermilion Bird · animal: river-deer"
      },
      {
        "sky": "Japan",
        "name": "柳宿",
        "meaning": "(grimoire: Nuriko's mansion)"
      }
    ],
    "electionLore": "the honest read — the old electors were wary of this station (it \"hinders travel\"; they marked it for discord). The Lion's eye misses nothing, and medieval calendar-keepers found that uncomfortable. Picatrix: harming harvests and travelers (hostile flag — firmly on the history shelf).",
    "birthEntry": "(continuity: this keeps the site's beloved line.) your mansion is The Glance — the lion's eye, with china's willow bending beside it. a noticing moon: one look from you and people feel seen. that's a real power — and it's why the old calendar-keepers were a little nervous of this station. nothing gets past you: not the detail, not the subtext, not the friend pretending they're fine. the willow bends; the eye doesn't blink ✦",
    "dailyCrossing": "the moon is at The Glance tonight — the lion's unblinking eye. a noticing day: read the room, catch the detail, check on the friend who says they're fine. the old books called this station too sharp for big launches — so watch today, and move tomorrow ♡",
    "tags": [
      "perception",
      "empathy",
      "detail",
      "watchfulness"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "river-deer",
    "guardianSky": "Vermilion Bird (South/Summer)",
    "hunger": {
      "deity": "the Nāgas, serpents of hidden knowledge",
      "symbol": "coiled serpent"
    },
    "signSpan": "12°51' Cnc – 25°43' Cnc"
  },
  {
    "station": 9,
    "epithet": "The Throne",
    "slug": "the-throne",
    "kanji": "星宿",
    "position": "25°43′ Cancer – 8°34′ Leo",
    "stars": "the Lion's brow — ζ, γ, η, α Leonis, including Regulus, the Little King · determinant η Leo",
    "match": null,
    "crossCultural": [
      {
        "sky": "Japan",
        "name": "星宿 (Hotohori)",
        "meaning": "\"the Star\" mansion"
      },
      {
        "sky": "Arabia",
        "name": "al-Jabha",
        "meaning": "\"the Forehead of the Lion\" — the brow of the old-Arab super-Lion that sprawled across a third of the sky"
      },
      {
        "sky": "India",
        "name": "Maghā",
        "meaning": "\"the Mighty\" · deity: the ancestors · symbol: the royal throne · star Regulus — STRONG"
      },
      {
        "sky": "China",
        "name": "星 Xīng",
        "meaning": "Vermilion Bird · animal: horse · det. Alphard, the Serpent's heart — DIVERGENT"
      }
    ],
    "electionLore": "Favorable for trade and building. Agrippa: \"strengthens buildings,\" love, benevolence. Picatrix: love and alliance.",
    "birthEntry": "your mansion is 星宿 — in fushigi yūgi, that's hotohori. the emperor. fitting: Regulus lives here, the little king, the royal star, and india crowned this same star Maghā — the royal throne. arabia saw the forehead of a Lion so huge it took a third of the sky. a courage moon: you face things head-on, crown-first. and here's the receipt — the old calendars gave every mansion thirteen days. yours got fourteen. even the calendar gave the lion an extra day ✦",
    "dailyCrossing": "the moon is in 星宿 tonight — the lion's forehead, the little king's star. a crown-first day: tradition says good for building things meant to last, and for standing by your people. walk in like the calendar gave you an extra day — because for this mansion, it did ♡",
    "tags": [
      "courage",
      "building",
      "loyalty",
      "standing-tall"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "horse",
    "guardianSky": "Vermilion Bird (South/Summer)",
    "hunger": {
      "deity": "Pitṛs (ancestors)",
      "symbol": "royal throne"
    },
    "signSpan": "25°43' Cnc – 8°34' Leo"
  },
  {
    "station": 10,
    "epithet": "The Mane",
    "slug": "the-mane",
    "kanji": "張宿",
    "position": "8°34′ Leo – 21°26′ Leo",
    "stars": "δ, θ Leo (Zosma)",
    "match": null,
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Zubra / al-Kharātān",
        "meaning": "\"the Mane\" — the Lion's glorious ruff"
      },
      {
        "sky": "India",
        "name": "P. Phālgunī",
        "meaning": "δ/θ Leo"
      },
      {
        "sky": "China",
        "name": "張 Zhāng",
        "meaning": "\"the Extended Net\" · Vermilion Bird · animal: deer"
      },
      {
        "sky": "Japan",
        "name": "張宿",
        "meaning": "(grimoire: Chiriko's mansion)"
      }
    ],
    "electionLore": "travel, commerce, and — the station's loveliest theme — the release of captives. Picatrix: freeing captives, wealth; sieges (mixed flag).",
    "birthEntry": "your mansion is The Mane — the lion's magnificent ruff, the volume, the aura, the hair that walks in before you do. and here's the deeper cut: the old tradition marks this station for the release of captives. mane energy is liberation energy — you make people feel like they can finally let their hair down, say the thing, be the size they actually are. main-character presence, used generously ✦",
    "dailyCrossing": "the moon moves through The Mane tonight. a letting-loose day: tradition calls it good for commerce, travel, and setting things free. untie something — including yourself ♡",
    "tags": [
      "presence",
      "liberation",
      "generosity",
      "confidence"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "deer",
    "guardianSky": "Vermilion Bird (South/Summer)",
    "hunger": {
      "deity": "Bhaga, of allotted fortune",
      "symbol": "front legs of a bed"
    },
    "signSpan": "8°34' Leo – 21°26' Leo"
  },
  {
    "station": 11,
    "epithet": "The Turning",
    "slug": "the-turning",
    "kanji": "翼宿",
    "position": "21°26′ Leo – 4°17′ Virgo",
    "stars": "Denebola (β Leo)",
    "match": null,
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Ṣarfa",
        "meaning": "\"the Turning (of the heat)\""
      },
      {
        "sky": "India",
        "name": "U. Phālgunī",
        "meaning": "Denebola"
      },
      {
        "sky": "China",
        "name": "翼 Yì",
        "meaning": "\"the Wings\" · Vermilion Bird · animal: snake"
      },
      {
        "sky": "Japan",
        "name": "翼宿",
        "meaning": "(grimoire: Tasuki's mansion — the wings suit him)"
      }
    ],
    "electionLore": "harvests and household matters; bad for sea travel. Picatrix: crops increased, ships harmed (mixed flag).",
    "birthEntry": "your mansion is The Turning — denebola, the lion's tail-star, where the old calendars said the summer heat finally turns away. you're a hinge person: the one in the group when everything changes — the mood, the season, the plan, the vibe. change doesn't happen to you; it happens through you. china drew wings here. of course it did ✦",
    "dailyCrossing": "the moon is at The Turning tonight — the star where the heat breaks. a hinge day: good for harvesting what's ready and letting the season change. (tradition says skip the boat.) turn the page ♡",
    "tags": [
      "change",
      "harvest",
      "transition",
      "momentum"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "snake",
    "guardianSky": "Vermilion Bird (South/Summer)",
    "hunger": {
      "deity": "Aryaman, of kinship and contract",
      "symbol": "back legs of a bed"
    },
    "signSpan": "21°26' Leo – 4°17' Vir"
  },
  {
    "station": 12,
    "epithet": "The Hand",
    "slug": "the-hand",
    "kanji": "軫宿",
    "position": "4°17′ Virgo – 17°09′ Virgo",
    "stars": "β, η, γ, δ, ε Vir",
    "match": null,
    "crossCultural": [
      {
        "sky": "India",
        "name": "Hasta",
        "meaning": "\"the Hand\" — skill, craft, the maker's touch (Corvus)"
      },
      {
        "sky": "Arabia",
        "name": "al-ʿAwwāʾ",
        "meaning": "\"the Barker / the Bend\" — the curve of stars in Virgo"
      },
      {
        "sky": "China",
        "name": "軫 Zhěn",
        "meaning": "\"the Chariot-board\" · Vermilion Bird · animal: earthworm"
      },
      {
        "sky": "Japan",
        "name": "軫宿",
        "meaning": "(grimoire: Mitsukake's mansion — the healer, on the hand station; the resonance writes itself)"
      }
    ],
    "electionLore": "benevolence, gain, voyages, and freedom. Picatrix: trade, harvests, freeing captives — gentle throughout.",
    "birthEntry": "your mansion is The Hand — india's Hasta, the station of skill and the maker's touch. everything you love passes through your hands: the drawing, the craft, the fixed zipper, the perfect gift, the comment that steadies a friend. the old tradition marks this station for benevolence and freedom — making as a form of kindness. the fan artists of the world are disproportionately yours, and we love them ✦",
    "dailyCrossing": "the moon rests in The Hand tonight — the maker's station. tradition calls today good for craft, generosity, and gain. make the thing. post the thing ✦",
    "tags": [
      "craft",
      "making",
      "generosity",
      "skill"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "earthworm",
    "guardianSky": "Vermilion Bird (South/Summer)",
    "hunger": {
      "deity": "Savitṛ, the impeller who sets things moving",
      "symbol": "an open hand"
    },
    "signSpan": "4°17' Vir – 17°09' Vir"
  },
  {
    "station": 13,
    "epithet": "The Jewel",
    "slug": "the-jewel",
    "kanji": "角宿",
    "position": "17°09′ Virgo – 0°00′ Libra",
    "stars": "Spica (α Vir)",
    "match": "STRONG",
    "crossCultural": [
      {
        "sky": "India",
        "name": "Chitrā",
        "meaning": "\"the brilliant one\" — the jewel. Spica"
      },
      {
        "sky": "Arabia",
        "name": "al-Simāk al-Aʿzal",
        "meaning": "\"the Unarmed High One\" — the tall star that carries no weapon (its twin, Arcturus, is al-Simāk the Lance-bearer)"
      },
      {
        "sky": "China",
        "name": "角 Jiǎo",
        "meaning": "\"the Horn\" · Azure Dragon's own horn · animal: flood-dragon"
      },
      {
        "sky": "Japan",
        "name": "角宿",
        "meaning": "(grimoire: Suboshi's mansion — and his twin Amiboshi holds the next station, 亢宿; the sky seated the twins side by side)"
      }
    ],
    "electionLore": "love, marriage, healing the sick, justice, and the safety of sailors. Picatrix: marital love, cures.",
    "birthEntry": "your mansion is The Jewel — spica, which india names Chitrā, the brilliant one. but the arabic name is the part to keep: al-Simāk al-Aʿzal, the unarmed high one — the tall bright star that carries no weapon, while its twin across the sky holds a lance. that's your kind of brilliance: you shine without needing to win. the old tradition gives this station love, healing, and justice — the sharp things, held gently ✦",
    "dailyCrossing": "the moon touches The Jewel tonight — spica, the unarmed high one. a shining day: tradition calls it good for love, healing, and putting things right. be brilliant. bring no weapon ♡",
    "tags": [
      "brilliance",
      "healing",
      "justice",
      "grace"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "flood-dragon",
    "guardianSky": "Azure Dragon (East/Spring)",
    "hunger": {
      "deity": "Tvaṣṭṛ, the divine artisan",
      "symbol": "a bright jewel"
    },
    "signSpan": "17°09' Vir – 0°00' Lib"
  },
  {
    "station": 14,
    "epithet": "The Veil",
    "slug": "the-veil",
    "kanji": "亢宿",
    "position": "0°00′ Libra – 12°51′ Libra",
    "stars": "ι, κ, λ Vir",
    "match": null,
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Ghafr",
        "meaning": "\"the Cover / the Veil\""
      },
      {
        "sky": "India",
        "name": "Svātī",
        "meaning": "Arcturus — the bright one that stands apart"
      },
      {
        "sky": "China",
        "name": "亢 Kàng",
        "meaning": "\"the Neck\" of the Azure Dragon · animal: dragon"
      },
      {
        "sky": "Japan",
        "name": "亢宿",
        "meaning": "(grimoire: Amiboshi's mansion — the gentle twin)"
      }
    ],
    "electionLore": "digging, wells, and the finding of treasure; hinders travel. Picatrix: treasure and wells; separation (mixed flag).",
    "birthEntry": "your mansion is The Veil — the covered station, named for what it doesn't show. its election lore is digging and buried treasure, and that's the whole read: your best work lives under the surface. the drafts folder. the private playlist. the twelve-layer inner life behind the calm face. people who earn their way past the veil never quite recover from what they find ✦",
    "dailyCrossing": "the moon slips behind The Veil tonight. a digging day: tradition calls it good for wells, treasure, and things beneath the surface — and bad for travel. stay in. open the drafts folder ♡",
    "tags": [
      "depth",
      "privacy",
      "treasure",
      "quiet-power"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "dragon",
    "guardianSky": "Azure Dragon (East/Spring)",
    "hunger": {
      "deity": "Vāyu, the wind",
      "symbol": "a young shoot in wind"
    },
    "signSpan": "0°00' Lib – 12°51' Lib"
  },
  {
    "station": 15,
    "epithet": "The Claws",
    "slug": "the-claws",
    "kanji": "氐宿",
    "position": "12°51′ Libra – 25°43′ Libra",
    "stars": "α, β Lib — Zubenelgenubi and Zubeneschamali, \"the southern claw\" and \"the northern claw\"",
    "match": "STRONG",
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Zubānā",
        "meaning": "\"the Claws (of the Scorpion)\""
      },
      {
        "sky": "India",
        "name": "Viśākhā",
        "meaning": "α/β/γ Lib"
      },
      {
        "sky": "China",
        "name": "氐 Dǐ",
        "meaning": "\"the Foundation\" · Azure Dragon · animal: raccoon-dog"
      },
      {
        "sky": "Japan",
        "name": "氐宿",
        "meaning": "(grimoire: Tomo's mansion)"
      }
    ],
    "electionLore": "hinders journeys and marriage — but good for freeing captives. Picatrix: discord, crop destruction (hostile flags — history shelf).",
    "birthEntry": "your mansion is The Claws — two bright stars the old skies read two ways at once: a scorpion's grip, and a set of scales. babylon saw both; greece kept the claws; rome restored the balance. both things are true about you. you know exactly what's yours, what isn't, and when to let go — and the old tradition marks this station for freeing captives, which is the claws' secret: they're not for grabbing. they're for holding the line, and for opening ✦",
    "dailyCrossing": "the moon crosses The Claws tonight — the grip that became the scales. a boundaries day: tradition calls it good for letting things go and setting things free. loosen a grip — maybe your own ♡",
    "tags": [
      "boundaries",
      "release",
      "fairness",
      "self-respect"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "raccoon-dog",
    "guardianSky": "Azure Dragon (East/Spring)",
    "hunger": {
      "deity": "Indrāgnī, force and fire as one",
      "symbol": "triumphal arch"
    },
    "signSpan": "12°51' Lib – 25°43' Lib"
  },
  {
    "station": 16,
    "epithet": "The Crown",
    "slug": "the-crown",
    "kanji": "房宿",
    "position": "25°43′ Libra – 8°34′ Scorpio",
    "stars": "β, δ, π Sco",
    "match": "STRONG",
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Iklīl",
        "meaning": "\"the Crown (of the Scorpion)\" — the diadem across its brow"
      },
      {
        "sky": "India",
        "name": "Anurādhā",
        "meaning": "β/δ/π Sco"
      },
      {
        "sky": "China",
        "name": "房 Fáng",
        "meaning": "\"the Room\" · Azure Dragon · animal: rabbit"
      },
      {
        "sky": "Japan",
        "name": "房宿",
        "meaning": "(grimoire: Soi's mansion)"
      }
    ],
    "electionLore": "fortune, love of long duration, buildings, armies — the durability station. Picatrix: long-lasting love, sailor safety.",
    "birthEntry": "your mansion is The Crown — three stars in a perfect row across the scorpion's brow, and one of the few stations every old sky agreed on completely. its signature in the election books is love of long duration: not the spark, the keeping. you're the decade-long friendship, the fandom you never quit, the promise that still holds. things built under your crown are built to last ✦",
    "dailyCrossing": "the moon wears The Crown tonight. a build-to-last day: tradition calls it good for lasting love, strong foundations, and promises that stick. say the thing you mean to keep ♡",
    "tags": [
      "loyalty",
      "endurance",
      "promises",
      "foundations"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "rabbit",
    "guardianSky": "Azure Dragon (East/Spring)",
    "hunger": {
      "deity": "Mitra, god of friendship and sworn alliance",
      "symbol": "archway · lotus"
    },
    "signSpan": "25°43' Lib – 8°34' Sco"
  },
  {
    "station": 17,
    "epithet": "The Heart",
    "slug": "the-heart",
    "kanji": "心宿",
    "position": "8°34′ Scorpio – 21°26′ Scorpio",
    "stars": "Antares — Qalb al-ʿAqrab, the Scorpion's heart",
    "match": "STRONG",
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Qalb",
        "meaning": "\"the Heart\" — Antares, red in the scorpion's chest"
      },
      {
        "sky": "India",
        "name": "Jyeṣṭhā",
        "meaning": "Antares"
      },
      {
        "sky": "China",
        "name": "心 Xīn",
        "meaning": "\"the Heart\" · Azure Dragon · animal: fox"
      },
      {
        "sky": "Japan",
        "name": "心宿",
        "meaning": "(grimoire: Nakago's mansion — yes, the villain got the heart; discuss)"
      }
    ],
    "electionLore": "victory over enemies — with the honest warning that the same books mark it for sedition and discord. A heart this strong needs aiming. Picatrix: victory; conspiracies (mixed flag).",
    "birthEntry": "your mansion is The Heart — antares, the red star burning in the scorpion's chest. two skies that never met both looked at it and said the same word: heart. that's you: all-in feelings, chest-first decisions, loyalty at full saturation. the old books say this station wins its battles — and warn, gently, that not every battle needs fighting. aim the heart. it always lands ✦",
    "dailyCrossing": "the moon is in The Heart tonight — the red star two skies named the same. a full-feeling day: courage comes easy, so pick the fight that matters or skip the fight entirely. lead with the chest, steer with the head ♡",
    "tags": [
      "passion",
      "courage",
      "loyalty",
      "intensity"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "fox",
    "guardianSky": "Azure Dragon (East/Spring)",
    "hunger": {
      "deity": "Indra, king of the gods",
      "symbol": "amulet · umbrella"
    },
    "signSpan": "8°34' Sco – 21°26' Sco"
  },
  {
    "station": 18,
    "epithet": "The Root",
    "slug": "the-root",
    "kanji": "尾宿",
    "position": "21°26′ Scorpio – 4°17′ Sagittarius",
    "stars": "λ, υ Sco — Shaula, the raised sting",
    "match": "STRONG",
    "crossCultural": [
      {
        "sky": "India",
        "name": "Mūla",
        "meaning": "\"the Root\" — the tail-region of the Scorpion"
      },
      {
        "sky": "Arabia",
        "name": "al-Shawla",
        "meaning": "\"the Sting\" — the raised barb"
      },
      {
        "sky": "China",
        "name": "尾 Wěi",
        "meaning": "\"the Tail\" · Azure Dragon · animal: tiger"
      },
      {
        "sky": "Japan",
        "name": "尾宿",
        "meaning": "(grimoire: Ashitare's mansion)"
      }
    ],
    "electionLore": "the martial end of the scorpion — sieges, pursuit; the old electors kept peace-work away from it. Picatrix: armies, ship-harm (hostile flags — history shelf).",
    "birthEntry": "your mansion is The Root — india's Mūla, at the deepest bend of the scorpion's tail. where others skim, you dig: to the cause, the origin, the real reason, the bottom of the mystery. arabia saw the sting here, and that's fair — truth at the root can sting. but somebody in every group has to be willing to go all the way down, and it was always going to be you ✦",
    "dailyCrossing": "the moon reaches The Root tonight — the deepest station of the tail. a digging day: get to the bottom of the thing. (the old books say it's no day for peace talks — save the treaty for tomorrow.) ♡",
    "tags": [
      "depth",
      "truth",
      "origins",
      "persistence"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "tiger",
    "guardianSky": "Azure Dragon (East/Spring)",
    "hunger": {
      "deity": "Nirṛti in practice, Prajāpati in the oldest text (§4)",
      "symbol": "a bundle of tied roots"
    },
    "signSpan": "21°26' Sco – 4°17' Sgr"
  },
  {
    "station": 19,
    "epithet": "The Flock",
    "slug": "the-flock",
    "kanji": "箕宿",
    "position": "4°17′ Sagittarius – 17°09′ Sagittarius",
    "stars": "eight stars in Sgr, two groups of four",
    "match": null,
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Naʿāʾim",
        "meaning": "\"the Ostriches\" — four walking to the river to drink, four walking back"
      },
      {
        "sky": "India",
        "name": "P. Aṣāḍhā",
        "meaning": "δ/ε Sgr"
      },
      {
        "sky": "China",
        "name": "箕 Jī",
        "meaning": "\"the Winnowing Basket\" · Azure Dragon · animal: leopard"
      },
      {
        "sky": "Japan",
        "name": "箕宿",
        "meaning": "(grimoire: Miboshi's mansion)"
      }
    ],
    "electionLore": "the taming of animals, construction — and the ending of disagreements. Picatrix: taming beasts, reconciliation.",
    "birthEntry": "your mansion is The Flock — eight ostrich-stars at the bank of the milky way: four walking to the river to drink, four walking home. nobody lost, nobody left. that's your whole deal: you keep the group together. the old books mark this station for calming wild things and ending disagreements — you're the one who gets the group chat back on speaking terms. winter is survived together, and you're why ✦",
    "dailyCrossing": "the moon walks with The Flock tonight — the ostriches at the sky-river. a together day: good for group projects, calming chaos, and ending an argument. check that everyone made it back from the river ♡",
    "tags": [
      "community",
      "peacemaking",
      "care",
      "togetherness"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "leopard",
    "guardianSky": "Azure Dragon (East/Spring)",
    "hunger": {
      "deity": "Āpas, the divine waters",
      "symbol": "elephant tusk · fan"
    },
    "signSpan": "4°17' Sgr – 17°09' Sgr"
  },
  {
    "station": 20,
    "epithet": "The Empty District",
    "slug": "the-empty-district",
    "kanji": "斗宿",
    "position": "17°09′ Sagittarius – 0°00′ Capricorn",
    "stars": "none. The famous starless stretch of sky; π Sgr stands at its edge as a marker.",
    "match": null,
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "al-Balda",
        "meaning": "\"the Empty District\" — the sky's deliberate blank"
      },
      {
        "sky": "India",
        "name": "U. Aṣāḍhā",
        "meaning": "ζ/σ Sgr"
      },
      {
        "sky": "China",
        "name": "斗 Dǒu",
        "meaning": "\"the Dipper\" · Black Tortoise · animal: xiezhi"
      },
      {
        "sky": "Japan",
        "name": "斗宿",
        "meaning": "(grimoire: Hikitsu's mansion)"
      }
    ],
    "electionLore": "harvests, gain, buildings, travel — a productive station despite the blankness. (Agrippa alone adds a separations warning — , mixed flag, history shelf.)",
    "birthEntry": "your mansion has no stars. that's not a mistake — that's the point. the old arab astronomers mapped twenty-eight stations and left one deliberately blank: The Empty District, the sky's rest stop. you're the pause that makes the music work. the blank page everyone else is scared of and you're not. the deep breath in the group chat. and your station's ancient winter saying is, honestly, a whole personality: \"cream is eaten, and cold is told to calm.\" be the calm. eat the cream ♡",
    "dailyCrossing": "the moon rests in The Empty District tonight — the starless field. a quiet day, and a productive one: tradition calls it good for building and harvesting, gently. no rush. cream is eaten; cold is told to calm ✦",
    "tags": [
      "rest",
      "space",
      "calm",
      "quiet-productivity"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "xiezhi",
    "guardianSky": "Black Tortoise (North/Winter)",
    "hunger": {
      "deity": "the Viśvedevas, the all-gods together",
      "symbol": "elephant tusk"
    },
    "signSpan": "17°09' Sgr – 0°00' Cap"
  },
  {
    "station": 21,
    "epithet": "The Listener",
    "slug": "the-listener",
    "kanji": "牛宿",
    "position": "0°00′ Capricorn – 12°51′ Capricorn",
    "stars": "α, β Cap (Giedi, Dabih)",
    "match": null,
    "crossCultural": [
      {
        "sky": "India",
        "name": "Śravaṇa",
        "meaning": "\"the ear — the listening one\"  · Altair"
      },
      {
        "sky": "Arabia",
        "name": "Saʿd al-Dhābiḥ",
        "meaning": "\"Luck of the Slaughterer\" — the old herding calendar's hard-season station, named plainly for midwinter's work; kept in the depth layer, told honestly, not dwelled on"
      },
      {
        "sky": "China",
        "name": "牛 Niú",
        "meaning": "\"the Ox\" · Black Tortoise · animal: ox"
      },
      {
        "sky": "Japan",
        "name": "牛宿",
        "meaning": "the 27/28 fault line itself — the station the sukuyō system dropped (grimoire: FY warrior Inami)"
      }
    ],
    "electionLore": "escape, release, and the curing of disease. Picatrix: liberation of captives, cures.",
    "birthEntry": "your mansion is The Listener — india's Śravaṇa, the ear of the sky, hung on altair. your station's nights are the coldest of the year: so cold, the old desert saying goes, that no barking dog stays outdoors. in that kind of quiet, someone has to be the one who hears. it's you. you catch what people mean, not just what they say — and the old books mark this station for cures, because being truly heard is half of healing ✦",
    "dailyCrossing": "the moon is with The Listener tonight — the sky's ear, in the year's quietest cold. a listening day: tradition calls it good for release and recovery. let someone finish their sentence. the quiet is working ♡",
    "tags": [
      "listening",
      "healing",
      "release",
      "quiet"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "ox",
    "guardianSky": "Black Tortoise (North/Winter)",
    "hunger": {
      "deity": "Viṣṇu, who crossed the worlds in three strides",
      "symbol": "an ear · three footprints"
    },
    "signSpan": "0°00' Cap – 12°51' Cap"
  },
  {
    "station": 22,
    "epithet": "The Drum",
    "slug": "the-drum",
    "kanji": "女宿",
    "position": "12°51′ Capricorn – 25°43′ Capricorn",
    "stars": "ε, μ, ν Aqr (Albali)",
    "match": null,
    "crossCultural": [
      {
        "sky": "India",
        "name": "Dhaniṣṭhā",
        "meaning": "its symbol is the drum  · Delphinus"
      },
      {
        "sky": "Arabia",
        "name": "Saʿd Bulaʿ",
        "meaning": "\"Luck of the Swallower\" — the star that swallows the rain"
      },
      {
        "sky": "China",
        "name": "女 Nǚ",
        "meaning": "\"the Girl\" · Black Tortoise · animal: bat"
      },
      {
        "sky": "Japan",
        "name": "女宿",
        "meaning": "(grimoire: Uruki's mansion — the lead of Genbu Kaiden)"
      }
    ],
    "electionLore": "release, liberation, healing (the freeing themes; the old books' harder separation uses stay glossed on the history shelf). Picatrix: liberation, healing.",
    "birthEntry": "your mansion is The Drum — india heard percussion at this station and hung it on the little dolphin constellation. rhythm-keeper: you set the tempo of whatever room you're in. and your station's old saying marks the exact day the year's beat comes back — late january, when \"the earth glistens\" with the first shimmer of spring. release what's off-beat, keep what grooves. you always know when the drop hits ♪",
    "dailyCrossing": "the moon taps The Drum tonight. a rhythm day: tradition calls it good for release, healing, and starting the song again. the earth glistens; the tempo returns ♪",
    "tags": [
      "rhythm",
      "music",
      "release",
      "renewal"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "bat",
    "guardianSky": "Black Tortoise (North/Winter)",
    "hunger": {
      "deity": "the eight Vasus, gods of abundance",
      "symbol": "a drum"
    },
    "signSpan": "12°51' Cap – 25°43' Cap"
  },
  {
    "station": 23,
    "epithet": "The Void",
    "slug": "the-void",
    "kanji": "虛宿",
    "position": "25°43′ Capricorn – 8°34′ Aquarius",
    "stars": "β Aqr — still named Sadalsuud — + ξ Aqr",
    "match": null,
    "crossCultural": [
      {
        "sky": "Japan",
        "name": "虛宿 (Tomite)",
        "meaning": "via the Chinese station: the Void, Emptiness"
      },
      {
        "sky": "China",
        "name": "虛 Xū",
        "meaning": "\"Emptiness\" · Black Tortoise of the North · animal: rat · same determinant star, β Aqr"
      },
      {
        "sky": "Arabia",
        "name": "Saʿd al-Suʿūd",
        "meaning": "\"the Luckiest of the Lucky\" — the grandest of the ten Saʿd (luck) asterisms"
      },
      {
        "sky": "India",
        "name": "Śatabhiṣā",
        "meaning": "\"the hundred physicians\" · deity Varuṇa · symbol: an empty circle (neighboring star — PARTIAL)"
      }
    ],
    "electionLore": "\"One of the most fortunate mansions — marriage, love, trade; favorable for all good intentions.\" Robson: build, marry, make friends, travel. Picatrix: goodwill between spouses, increase of trade.",
    "birthEntry": "your mansion is 虛宿 — the Void. before you panic: the arabic sky called this exact star Saʿd al-Suʿūd, the luckiest of the lucky, and the indian sky saw a hundred healers holding an empty circle. same star. maybe luck is just an open space where something kind can land — and you're the open space. the old desert calendars sang that when your star rises, \"everything frozen melts, and water runs through the plants.\" thaw energy. rooms soften when you walk in ✦",
    "dailyCrossing": "the moon is in 虛宿 tonight — the void that arabia called the luckiest of the lucky. tradition calls today good for nearly every kind intention: build, mend, begin. if something's been frozen, today it loosens ♡",
    "tags": [
      "luck",
      "beginnings",
      "mending",
      "love"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "rat",
    "guardianSky": "Black Tortoise (North/Winter)",
    "hunger": {
      "deity": "Varuṇa",
      "symbol": "empty circle"
    },
    "signSpan": "25°43' Cap – 8°34' Aqr"
  },
  {
    "station": 24,
    "epithet": "The Hideaway",
    "slug": "the-hideaway",
    "kanji": "危宿",
    "position": "8°34′ Aquarius – 21°26′ Aquarius",
    "stars": "γ, π, ζ, η Aqr — the little \"tent\" asterism (Sadachbia)",
    "match": null,
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "Saʿd al-Akhbiya",
        "meaning": "\"Luck of the Tents / of Hidden Things\""
      },
      {
        "sky": "India",
        "name": "P. Bhādrapadā",
        "meaning": "α/β Peg"
      },
      {
        "sky": "China",
        "name": "危 Wēi",
        "meaning": "\"the Rooftop\" · Black Tortoise · animal: swallow"
      },
      {
        "sky": "Japan",
        "name": "危宿",
        "meaning": "(grimoire: Urumiya's mansion — held by two warriors at once, Hagas & Tegu)"
      }
    ],
    "electionLore": "protection and hiding — what's inside the tent is safe. Agrippa/Picatrix mark it for sieges and binding (hostile flags — history shelf only).",
    "birthEntry": "your mansion is The Hideaway — four stars pitching a small tent in aquarius, the luck of hidden things. you're the keeper of safe places: the room people can cry in, the blanket fort that fixes a bad tuesday, the group chat where it's okay to be soft. your station's spring saying is \"snakes emerge and maidens spin\" — the world wakes up out there, and the real magic happens in here ✦",
    "dailyCrossing": "the moon shelters in The Hideaway tonight. a nest day: keep soft things safe, tend the fort. the world can wait outside the tent ♡",
    "tags": [
      "sanctuary",
      "protection",
      "coziness",
      "care"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "swallow",
    "guardianSky": "Black Tortoise (North/Winter)",
    "hunger": {
      "deity": "Aja Ekapāda, the one-footed fire-pillar",
      "symbol": "front legs of a cot"
    },
    "signSpan": "8°34' Aqr – 21°26' Aqr"
  },
  {
    "station": 25,
    "epithet": "The Chamber",
    "slug": "the-chamber",
    "kanji": "室宿",
    "position": "21°26′ Aquarius – 4°17′ Pisces",
    "stars": "α, β Peg (Markab, Scheat) — the first wall of the Great Square of Pegasus",
    "match": null,
    "crossCultural": [
      {
        "sky": "China",
        "name": "室 Shì",
        "meaning": "\"the Room / the Encampment\" — the Great Square begins"
      },
      {
        "sky": "Arabia",
        "name": "al-Fargh al-Muqaddam",
        "meaning": "\"the Fore-Spout of the Bucket\" — the great dalw that pours the spring rain begins here"
      },
      {
        "sky": "India",
        "name": "U. Bhādrapadā",
        "meaning": "γ Peg / α And"
      },
      {
        "sky": "Japan",
        "name": "室宿",
        "meaning": "(grimoire: Hatsui's mansion)"
      }
    ],
    "electionLore": "the union of lovers, and goodwill. Picatrix: love-union, healing.",
    "birthEntry": "your mansion is The Chamber — china saw a room here, the first wall of the great square of pegasus, and arabia saw the front lip of the enormous bucket that pours out the spring rain. hosting energy, both ways: a room that holds people, a vessel that pours for them. the old books mark your station for union and goodwill — you make rooms feel like Rooms, and everyone relaxes two degrees when it's your place ✦",
    "dailyCrossing": "the moon enters The Chamber tonight — the room of stars. a gathering day: tradition calls it good for union and goodwill. get your people in one room. pour something out for them ♡",
    "tags": [
      "hospitality",
      "union",
      "goodwill",
      "gathering"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "pig",
    "guardianSky": "Black Tortoise (North/Winter)",
    "hunger": {
      "deity": "Ahirbudhnya, serpent of the deep foundation",
      "symbol": "back legs of a cot"
    },
    "signSpan": "21°26' Aqr – 4°17' Psc"
  },
  {
    "station": 26,
    "epithet": "The Guide",
    "slug": "the-guide",
    "kanji": "壁宿",
    "position": "4°17′ Pisces – 17°09′ Pisces",
    "stars": "γ Peg + α And (Algenib, Alpheratz) — the Square's far wall",
    "match": null,
    "crossCultural": [
      {
        "sky": "India",
        "name": "Revatī",
        "meaning": "deity Pūṣan, the guide of journeys · symbol: the fish · the last station of india's wheel"
      },
      {
        "sky": "Arabia",
        "name": "al-Fargh al-Muʾakhkhar",
        "meaning": "\"the Hind-Spout of the Bucket\" — the pour completes"
      },
      {
        "sky": "China",
        "name": "壁 Bì",
        "meaning": "\"the Wall\" · Black Tortoise · animal: yayu"
      },
      {
        "sky": "Japan",
        "name": "壁宿",
        "meaning": "(grimoire: Namame's mansion)"
      }
    ],
    "electionLore": "harvests, revenue, gain; favorable for marriage. (Hinders building — even guides don't pour foundations.) Picatrix: trade increase; sailor-caution (mixed flag).",
    "birthEntry": "your mansion is The Guide — india's Revatī, the last station of its wheel, whose deity Pūṣan walks every traveler safely home. that's your job in every group and you know it: the address in the chat, the \"text me when you're back,\" the one who remembers where everyone parked. the old books give your station harvests and happy endings — the rewards of journeys completed. everyone gets home. that's the whole religion ✦",
    "dailyCrossing": "the moon walks with The Guide tonight — the star that sees journeys home. a homeward day: finish the trip, gather the harvest, count your people in. text them when you're back ♡",
    "tags": [
      "guidance",
      "homecoming",
      "completion",
      "care"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "yayu",
    "guardianSky": "Black Tortoise (North/Winter)",
    "hunger": {
      "deity": "Pūṣan",
      "symbol": "fish"
    },
    "signSpan": "4°17' Psc – 17°09' Psc"
  },
  {
    "station": 27,
    "epithet": "The Thread",
    "slug": "the-thread",
    "kanji": "奎宿",
    "position": "17°09′ Pisces – 0°00′ Aries",
    "stars": "β And (Mirach)",
    "match": null,
    "crossCultural": [
      {
        "sky": "Arabia",
        "name": "Baṭn al-Ḥūt / al-Rishāʾ",
        "meaning": "two names at once: \"the Belly of the Fish\" and \"the Cord\" — the bucket-rope. The double name is the classic example of layered Bedouin sky-imagery"
      },
      {
        "sky": "India",
        "name": "—",
        "meaning": "the nakshatra wheel has already returned to Ashvinī; this stretch belongs to the closing"
      },
      {
        "sky": "China",
        "name": "奎 Kuí",
        "meaning": "\"the Stride\" · White Tiger · animal: wolf"
      },
      {
        "sky": "Japan",
        "name": "奎宿",
        "meaning": "(grimoire: Tokaki's mansion)"
      }
    ],
    "electionLore": "journeys, trade, and peace between spouses — the closing works. Picatrix: trade, marital peace, safe travel — gentle to the last.",
    "birthEntry": "your mansion is The Thread — the final station, the cord that ties the wheel closed. arabia gave it two names at once, the fish's belly and the bucket-rope, because the sky is layered and so are you. your station's old jobs are all the closing kind: safe journeys, fair trade, peace between people who love each other. every wheel needs someone who ties the knot at the end so the whole thing holds — that's you. and one station over, the gate opens, and everything begins again ✦",
    "dailyCrossing": "the moon ties The Thread tonight — the wheel's last knot. a closing day: finish the journey, make the peace, tie off the loose end. tomorrow: the gate, and the wheel turns new ♡",
    "tags": [
      "completion",
      "peace",
      "connection",
      "closure"
    ],
    "hasProse": true,
    "steps": null,
    "fragment": null,
    "animal": "wolf",
    "guardianSky": "White Tiger (West/Autumn)",
    "hunger": null,
    "signSpan": "17°09' Psc – 0°00' Ari"
  }
];
