// MANZIL · THE WALKER SHEET · 15 Sep 2026 · Design → Code · STATUS: FINAL v2 (15 Sep 2026: Measurement's six fixes applied; the awake clause moved off 37 intros into COPY.deal.awake)
// One record per walker, five fields, per the pack's part two §5: "a walker is four lines and a tell." The four lines
// are the slots the flow already uses; `them` is the pronoun the copy table's {them} placeholder reads (him · her · them).
//   in    · the line on the way in: what they do before they fight. Today: roster `line`.
//   tell  · the bubble on the road: their reaction, and a hint at how the mirror plays this rung. Today: roster `react`.
//   out   · the line on the way out: how they yield. Today: roster `defeat`.
//   next  · what the road says about them before you meet them AGAIN (a return after a loss). Today: roster `again`.
//           Empty = the road uses `in` (first meeting). Code: rbNextLine already falls back this way.
//   them  · him · her · them. Authored by Design, 15 Sep 2026. Rule: every walker takes the pronoun the sheet itself uses for them;
//           a quiet one whose lines never say she or he → them (21 of 27); the four written as she (the seventh, the last tenant,
//           the tower-heart, the house-watch) → her; the mave archetype → her. Every row is filled; rung.lost may use {them}.
// THE AWAKE CLAUSE IS OFF THE INTROS (15 Sep 2026, Design): "she gives nothing away twice, and holds your cards awake." (mave, 10)
// and "the hand is yours, every card of it awake." (quiet ones, 27) were one sentence of ladder canon repeated 37 times as
// character copy. It is now ONE deal line, COPY.deal.awake, fired on the seventh and eighth rungs; the intros are character only.
// DUPLICATE NAMES RESOLVED: m9 hessa → helda · m19 oda → orsa · m27 orin → corvin (the m2, m24 and m1 originals keep theirs).
// House 22 (the roof) is held pending the komi decision and has no roster; house 0 is the generic archetype list and
// is not a sheet. Counts: 216 walkers · them blank 0 · tell blank 0 · out blank 0 · next blank 0.
// The behavioural tell (does bekk really count the ground first?) is NOT a field yet: it is a claim about the mirror, and
// Measurement said it is a character only if the engine makes it true. A sixth field `plays` is reserved for it.

export const FIELDS = ["in", "tell", "out", "next", "them"];
export const WALKERS = {
  1: [
    { name: "orin", fig: "imra", them: "him",
      in: "orin is the porter. he leans on the open leaf, because in forty years nobody has asked him to close it.",
      tell: "orin shifts his weight on the door.",
      out: "orin waves you in without straightening up.",
      next: "orin nods. still leaning. still open." },
    { name: "sefa", fig: "sef", them: "her",
      in: "sefa takes the toll. she holds the bowl out upside down, so nobody is confused about the price.",
      tell: "sefa turns the bowl over, and back.",
      out: "sefa puts the bowl away. there was nothing in it.",
      next: "sefa has the bowl out. upside down." },
    { name: "dagan", fig: "odel", them: "him",
      in: "dagan carries the bar. it is on his shoulder, and it has been on his shoulder since he was given it, and it has never been in the brackets.",
      tell: "dagan shifts the bar to his other shoulder.",
      out: "dagan sets the bar down on the road, and you step over it.",
      next: "dagan has the bar up again. going nowhere." },
    { name: "miro", fig: "tesh", them: "him",
      in: "miro lights the arch. both torches, every dusk, so nobody coming in at night mistakes an open door for a wall.",
      tell: "miro trims a wick.",
      out: "miro lifts the pole and lights your way through.",
      next: "miro has both torches going for you." },
    { name: "halla", fig: "ruen", them: "her",
      in: "halla counts who comes in. the tally is full of marks and there is no column for turned away, because there has never been a need for one.",
      tell: "halla makes a mark.",
      out: "halla marks you in, and shows you the tally. everyone.",
      next: "halla has your mark ready." },
    { name: "tesk", fig: "brann", them: "him",
      in: "tesk is the crier. every hour he calls that the gate stands open, to a city that already knows.",
      tell: "tesk draws a breath to call.",
      out: "tesk calls the hour, and adds your name to it.",
      next: "tesk called you before you reached the arch." },
    { name: "the captain", fig: "mave", them: "her",
      in: "the captain of a gate that does not close. her sword is sheathed, her hands are behind her back,",
      tell: "the captain does not move her hands.",
      out: "the captain steps to one side of the arch. the other side was already clear.",
      next: "the captain is where she was, hands behind her back." },
    { name: "the dog's keeper", fig: "the quiet one", them: "them",
      in: "the dog's keeper holds a leash with no dog on it. the dog is in the gateway, and has been for longer than the keeper has been alive.",
      tell: "the keeper coils the leash again.",
      out: "the keeper steps back, and the dog does not get up, and you go through between them.",
      next: "still holding the leash. still no dog on it." },
  ],
  2: [
    { name: "hessa", fig: "imra", them: "her",
      in: "hessa has held the same clay token since the number wore off it. she is very sure it is her turn next.",
      tell: "hessa checks her token.",
      out: "hessa waves you past. she is not going anywhere.",
      next: "back again. hessa has not moved, and mentions it." },
    { name: "orv", fig: "sef", them: "him",
      in: "orv keeps the order of the queue on a tally stick. there are more notches on it than there have ever been people.",
      tell: "orv cuts another notch.",
      out: "orv writes you down as gone through.",
      next: "orv still has your notch. it is a little worn." },
    { name: "belu", fig: "odel", them: "him",
      in: "belu has carried the same bundle so long the cloth has gone to dust. he is not about to set it down at this stage.",
      tell: "belu shifts the bundle.",
      out: "belu steps aside, bundle and all.",
      next: "belu has kept his place. and the bundle." },
    { name: "sena", fig: "tesh", them: "her",
      in: "sena reads one letter over and over. she has known it by heart for a very long time and reads it anyway.",
      tell: "sena finds her place again.",
      out: "sena folds the letter and lets you by.",
      next: "sena was at the same line when you left." },
    { name: "tomek", fig: "ruen", them: "him",
      in: "tomek fell asleep leaning on his staff some centuries ago. the queue steps politely around him and has stopped bringing it up.",
      tell: "tomek does not wake.",
      out: "tomek sleeps through your crossing.",
      next: "tomek is exactly where he was. of course he is." },
    { name: "arda", fig: "brann", them: "her",
      in: "arda plays knucklebones against herself on a flat stone. she is winning, and also losing, and finds this funnier than she used to.",
      tell: "arda throws again.",
      out: "arda concedes the stone to you.",
      next: "arda kept your side of the board warm." },
    { name: "veda", fig: "mave", them: "her",
      in: "veda counts the stones of the lintel and gets a different number every night.",
      tell: "veda starts the count over.",
      out: "veda counts you through.",
      next: "veda counted you last time too. different number." },
    { name: "the one at the front", fig: "the quiet one", them: "them",
      in: "the one at the front has stood at the threshold longer than the stones have and has never once stepped through.",
      tell: "the one at the front does not turn round.",
      out: "the one at the front stands aside. one step, no more.",
      next: "still at the front. still not through." },
  ],
  3: [
    { name: "maia", fig: "imra", them: "her",
      in: "maia drives the sledge, and will not start it until everyone is on the floor. she counts heads twice.",
      tell: "maia counts heads again.",
      out: "maia stops the sledge and waves you across the floor.",
      next: "maia counts you in with the others this time." },
    { name: "elet", fig: "sef", them: "her",
      in: "elet binds the sheaves two at a time, never one. she says a sheaf alone falls over.",
      tell: "elet ties another pair.",
      out: "elet sets down the twine. two sheaves lean on each other behind her.",
      next: "elet has a pair ready for you." },
    { name: "tay", fig: "odel", them: "her",
      in: "tay winnows, and reads the wind for the others before she throws. nobody on this floor throws first.",
      tell: "tay wets a finger and holds it up.",
      out: "tay lets the wind take the chaff, and you go with it.",
      next: "tay has already read the wind. it is yours tonight." },
    { name: "alke", fig: "tesh", them: "her",
      in: "alke sings the count so the flails fall together. she has never once sung alone.",
      tell: "alke sings the next line.",
      out: "alke lets the song end, and you cross in the silence.",
      next: "alke starts the count with your name in it." },
    { name: "kel\u0101", fig: "ruen", them: "her",
      in: "kel\u0101 rakes the chaff and keeps the floor's edge. everyone else works inside the line she draws.",
      tell: "kel\u0101 rakes the edge straight again.",
      out: "kel\u0101 opens a gap in the rim for you.",
      next: "kel\u0101 has left the gap open." },
    { name: "aste", fig: "brann", them: "her",
      in: "aste carries the water and gives it to everyone else before she drinks. she is always the last to drink.",
      tell: "aste offers the jar around.",
      out: "aste hands you the jar. you drink first, for once.",
      next: "aste has the jar out already." },
    { name: "the eldest", fig: "mave", them: "her",
      in: "the eldest sets the pace of the floor. the others watch her hands.",
      tell: "the eldest's hands do not change pace.",
      out: "the eldest slows the pace, and the floor lets you through.",
      next: "the eldest is where she was, and the pace is hers." },
    { name: "the seventh", fig: "the quiet one", them: "her",
      in: "the seventh sister is not on the floor tonight, or any night. her place is kept: the sledge stands where she would stand, and nobody takes it.",
      tell: "the seventh's place stays empty.",
      out: "the seventh's place stays empty, and you walk past it.",
      next: "still kept. still empty." },
  ],
  4: [
    { name: "nell", fig: "imra", them: "her",
      in: "nell carries the lantern for the one ahead of her and has never seen her face. she describes it beautifully.",
      tell: "nell lifts the lantern a little.",
      out: "nell steps out of the line to let you past, and steps straight back in.",
      next: "nell is still carrying it. still hasn't looked." },
    { name: "osk", fig: "sef", them: "him",
      in: "osk counts steps so the gap stays honest. eleven, always eleven. once it was ten and he has not forgiven himself.",
      tell: "osk counts under his breath.",
      out: "osk lets you through without losing count.",
      next: "eleven. osk nods." },
    { name: "pim", fig: "odel", them: "him",
      in: "pim carries the spare wick. nobody has ever asked for it. pim is ready.",
      tell: "pim checks the wick.",
      out: "pim offers you the wick. you do not need it. pim keeps it.",
      next: "pim has the wick. in case." },
    { name: "rahel", fig: "tesh", them: "her",
      in: "rahel joined the procession by accident, on her way somewhere else, and stayed on principle.",
      tell: "rahel shrugs.",
      out: "rahel waves you on. she was going this way anyway.",
      next: "rahel is still on her way somewhere else." },
    { name: "tal", fig: "ruen", them: "him",
      in: "tal thinks the procession is a race and is losing it, very slowly, to people who do not know they are in one.",
      tell: "tal lengthens his stride.",
      out: "tal lets you pass and counts it as a tactic.",
      next: "tal has gained no ground. tal has a plan." },
    { name: "hesper", fig: "brann", them: "her",
      in: "hesper writes down what the one ahead does, every night, in a book, in case it ever changes. it has not.",
      tell: "hesper makes a note.",
      out: "hesper writes you down and moves aside.",
      next: "hesper has your page. it says the same thing." },
    { name: "the red one", fig: "mave", them: "her",
      in: "the red one carries the only red lantern in the line and insists she is not at the front.",
      tell: "the red lantern does not move.",
      out: "the red one stands aside. she was never in front, she says.",
      next: "the red one is where she was. not in front." },
    { name: "the first lantern", fig: "the quiet one", them: "them",
      in: "the first lantern has never once turned round.",
      tell: "the first lantern does not turn.",
      out: "the first lantern stops. and, for the first time, turns.",
      next: "walking again. facing forward." },
  ],
  5: [
    { name: "tamsin", fig: "imra", them: "her",
      in: "tamsin heats the irons and has never once touched a horse. she knows the colour a mark wants by the sound the fire makes.",
      tell: "tamsin turns the iron a quarter turn.",
      out: "tamsin banks the fire and lets you past it.",
      next: "tamsin has the irons hot. she heard you coming." },
    { name: "bekk", fig: "sef", them: "him",
      in: "bekk holds the head. he has a scar from the one that would not be held, and he is proud of both.",
      tell: "bekk takes a firmer grip.",
      out: "bekk lets go of the rail. through you go.",
      next: "bekk remembers your grip. he has changed his." },
    { name: "ori", fig: "odel", them: "her",
      in: "ori keeps the tally-book of every mark the yard has made. there is one page nobody may read, and it is blank.",
      tell: "ori makes a mark in the book.",
      out: "ori writes you down, and turns the page.",
      next: "ori has your page open already." },
    { name: "sayen", fig: "tesh", them: "them",
      in: "sayen is the gelder. people are polite to sayen.",
      tell: "sayen says nothing, which is worse.",
      out: "sayen steps aside, politely. you are polite back.",
      next: "sayen nods. you nod. that is the whole conversation." },
    { name: "hult", fig: "ruen", them: "him",
      in: "hult cuts the brands themselves, the iron heads, and has never made two alike. he would like you to notice.",
      tell: "hult holds one up to the light.",
      out: "hult lets you by and shows you the newest one on the way.",
      next: "hult has a new one. he cut it after last time." },
    { name: "marra", fig: "brann", them: "her",
      in: "marra buys the marked and sells the unmarked, and says the difference is the whole trade.",
      tell: "marra names a price.",
      out: "marra waves you through. no charge, this once.",
      next: "marra remembers what you cost her." },
    { name: "the brander", fig: "mave", them: "her",
      in: "the brander's hand does not shake. it has not shaken in thirty years, and",
      tell: "the brander's hand does not move.",
      out: "the brander sets the iron down, handle toward you.",
      next: "the brander is where she was. hand steady." },
    { name: "the unbranded", fig: "the quiet one", them: "them",
      in: "the unbranded has stood in this yard for years and never once been marked, because nobody has ever managed to take hold of it.",
      tell: "the unbranded does not shy.",
      out: "the unbranded walks to the gate, and waits for you there.",
      next: "still in the yard. still unmarked." },
  ],
  6: [
    { name: "ashur", fig: "imra", them: "him",
      in: "ashur drives the herd, when there is a herd to drive. tonight he is crouched with his back to it, counting breaths until the rain lets up.",
      tell: "ashur counts another breath.",
      out: "ashur stands, at last, and the rain has thinned. he does not say he told you so.",
      next: "ashur is crouched again. still counting." },
    { name: "temi", fig: "sef", them: "her",
      in: "temi keeps the brand-iron. it lies across her lap, cold, because nothing gets marked in a storm and she is in no hurry to warm it.",
      tell: "temi turns the iron over in her lap.",
      out: "temi lifts the iron, looks at it, and puts it away unlit.",
      next: "temi has the iron across her knees. cold." },
    { name: "rook", fig: "odel", them: "him",
      in: "rook reads the cloud wall. he can tell you which way it is turning and how long it has left, and he will not tell you it is safe until it is.",
      tell: "rook tilts his head at the wall.",
      out: "rook points: there. the wall is opening, and you were standing in the right place.",
      next: "rook is reading the wall. it is turning." },
    { name: "isen", fig: "tesh", them: "her",
      in: "isen holds the well-rope. it hangs slack in her hands, because the well is full to the lip tonight and there is nothing to draw.",
      tell: "isen lets the rope out an inch.",
      out: "isen coils the rope. the well has given you what it had.",
      next: "isen has the rope. slack." },
    { name: "ghalib", fig: "ruen", them: "him",
      in: "ghalib lit no fire. he laid it, and looked at the sky, and left it laid. a fire in this is a thing you do for the look of it.",
      tell: "ghalib glances at the unlit fire.",
      out: "ghalib strikes the flint, once, and it takes. the rain is done.",
      next: "ghalib's fire is laid, and not lit." },
    { name: "suri", fig: "brann", them: "her",
      in: "suri sings the herd still. low, the same three notes, one hand flat on a wet neck, and not one of them has bolted.",
      tell: "suri does not stop singing.",
      out: "suri lets the song end. the herd stands, and lets you through it.",
      next: "suri is singing. the same three notes." },
    { name: "the old drover", fig: "mave", them: "her",
      in: "the old drover has one hand flat on the ground, feeling for the moment the rain stops.",
      tell: "the old drover does not lift her hand.",
      out: "the old drover lifts her hand off the ground and looks at the palm. dry.",
      next: "the old drover's hand is on the ground. waiting." },
    { name: "the stray", fig: "the quiet one", them: "them",
      in: "the stray stands in the rain, out past the herd, and does not mind it. nobody knows whose it was.",
      tell: "the stray does not come in out of the rain.",
      out: "the stray steps aside, wet through, and lets you into the dry.",
      next: "the stray is out in it. not minding." },
  ],
  7: [
    { name: "wenna", fig: "imra", them: "her",
      in: "wenna came back down off the hill with the herd and one fewer than she took up, and rang the bell at the gate anyway.",
      tell: "wenna rings the bell once.",
      out: "wenna swings the gate for you.",
      next: "wenna is at the gate with the bell." },
    { name: "josse", fig: "sef", them: "him",
      in: "josse came back from the war with a limp and a song, and plays the song on a whistle every night so the limp has company.",
      tell: "josse plays a bar.",
      out: "josse plays you up the road.",
      next: "josse has the whistle out." },
    { name: "amira", fig: "odel", them: "her",
      in: "amira came back to bury her mother and stayed. the spade is clean now and leans by the door.",
      tell: "amira touches the spade.",
      out: "amira steps back into the doorway and leaves it open.",
      next: "amira is in the doorway." },
    { name: "teodor", fig: "tesh", them: "him",
      in: "teodor went to sea for twelve years and came back with every tide-table in his head and no use for any of them.",
      tell: "teodor coils the rope again.",
      out: "teodor drops the coil and lets you by.",
      next: "teodor is coiling." },
    { name: "ilse", fig: "ruen", them: "her",
      in: "ilse ran off at fifteen and walked back at forty with one small bag, and nobody asked, and she has never said.",
      tell: "ilse shifts the bag to the other hand.",
      out: "ilse sets the bag down and does not pick it up.",
      next: "ilse has the bag." },
    { name: "bram", fig: "brann", them: "him",
      in: "bram comes back every night from the fields with the scythe on his shoulder and has never once been anywhere else, and says that counts.",
      tell: "bram shifts the scythe.",
      out: "bram lifts the scythe off his shoulder and stands it by the hedge.",
      next: "bram is coming in from the fields." },
    { name: "the one who waits up", fig: "mave", them: "her",
      in: "the one who waits up keeps a lamp in the window every night for whoever is on the road.",
      tell: "the lamp in the window is turned up.",
      out: "the lamp is set in the window for you.",
      next: "the lamp is lit already." },
    { name: "the one at the milestone", fig: "the quiet one", them: "them",
      in: "the one at the milestone sits on the last stone facing away from the village, and has not gone the last mile, and may yet.",
      tell: "the one at the milestone does not turn round.",
      out: "the one at the milestone stands up, and walks in ahead of you.",
      next: "still on the stone." },
  ],
  8: [
    { name: "perrin", fig: "imra", them: "him",
      in: "perrin carries the hay up from the barn in armfuls, and the last armful is always for the one at the back.",
      tell: "perrin shifts the armful.",
      out: "perrin drops the hay by your feet and steps back.",
      next: "perrin has an armful ready." },
    { name: "ollin", fig: "sef", them: "him",
      in: "ollin fills the trough and does not stop pouring until it runs over, so the small ones get a drink too.",
      tell: "ollin tips the bucket further.",
      out: "ollin sets the bucket down. the trough is full.",
      next: "ollin is pouring." },
    { name: "mab", fig: "odel", them: "her",
      in: "mab feeds the orphan lamb by hand, at midnight and at four, and has not slept a whole night since the spring.",
      tell: "mab tilts the bottle.",
      out: "mab tucks the lamb inside her coat and steps aside.",
      next: "mab has the bottle warm." },
    { name: "tarn", fig: "tesh", them: "him",
      in: "tarn breaks the ice on the water with a stone every morning before anything else is done.",
      tell: "tarn lifts the stone.",
      out: "tarn lets the stone fall, and the ice is broken for you.",
      next: "tarn's stone is raised." },
    { name: "dessa", fig: "ruen", them: "her",
      in: "dessa salts the lick and holds her hand out flat for the ones too shy to come to the stone.",
      tell: "dessa opens her hand.",
      out: "dessa holds the hand out to you.",
      next: "dessa's hand is out." },
    { name: "fen", fig: "brann", them: "her",
      in: "fen counts them in at the gap with a bit of bread for each, and no animal has ever been counted twice or missed.",
      tell: "fen tears off another piece.",
      out: "fen counts you in and gives you the last of the loaf.",
      next: "fen is counting." },
    { name: "the flockmaster", fig: "mave", them: "her",
      in: "the flockmaster stands at the gap with the crook and knows every animal by its walk.",
      tell: "the flockmaster's crook comes down.",
      out: "the flockmaster lifts the crook and the gap is open.",
      next: "the flockmaster is at the gap." },
    { name: "the one at the gap", fig: "the quiet one", them: "them",
      in: "the one at the gap sits on the wall in the mist and has sat there every night the fold has stood.",
      tell: "the one at the gap does not move.",
      out: "the one at the gap turns to look up the hill, and you pass.",
      next: "still on the wall." },
  ],
  9: [
    { name: "ada", fig: "imra", them: "her",
      in: "ada carries at night. the lantern is hooded so the road can see her before she sees it, which she says is only polite. she read the list and packed anyway.",
      tell: "ada lifts the hood a finger's width.",
      out: "ada hoods the lantern and walks on into it.",
      next: "ada is on the road. lantern hooded." },
    { name: "birun", fig: "sef", them: "him",
      in: "birun reads the almanac every evening and folds it away every evening. tonight it said not to travel. it is folded in his coat, where it always is.",
      tell: "birun's hand goes to the folded page.",
      out: "birun takes the page out, reads it once more, and puts it back without unfolding it.",
      next: "birun has the list. folded." },
    { name: "helda", fig: "odel", them: "her",
      in: "helda drives a herd that is not behind her. the crook is, and the whistle, and the habit of looking back to count. she counts anyway.",
      tell: "helda looks back and counts nothing.",
      out: "helda turns the crook over and walks on ahead of the herd she does not have.",
      next: "helda is here. crook up, nothing behind." },
    { name: "tolm", fig: "tesh", them: "him",
      in: "tolm walks the road backwards, watching where he has been. he says the thing that watches you is never in front. he has not tripped yet.",
      tell: "tolm's head turns a little further.",
      out: "tolm walks backwards past you, still watching the way you came.",
      next: "tolm is walking backwards. still." },
    { name: "senne", fig: "ruen", them: "her",
      in: "senne carries a sealed satchel and wears running shoes on a road nobody runs. the seal is not hers to break and the warning was not hers to read. she is late.",
      tell: "senne shifts the satchel to the other shoulder.",
      out: "senne runs. the eyes in the scrub follow her and do not close.",
      next: "senne is here. late." },
    { name: "iku", fig: "brann", them: "her",
      in: "iku set out with the others and stopped to look at something in the verge. that was some time ago. the others are far ahead and iku is still looking.",
      tell: "iku does not look round.",
      out: "iku looks away from the verge at last, and there is nothing there, and there never was.",
      next: "iku is sitting at the verge. looking." },
    { name: "the almanac-keeper", fig: "mave", them: "her",
      in: "the almanac-keeper wrote the list. she knows exactly what it says about tonight and she is walking under it with the book under her arm.",
      tell: "the almanac-keeper does not open the book.",
      out: "the almanac-keeper opens the book, finds tonight, and draws one line through it.",
      next: "the almanac-keeper is here. book closed." },
    { name: "the one at the verge", fig: "the quiet one", them: "them",
      in: "the one at the verge is half in the scrub and you have never seen more of them than the eyes. they have been there the whole way.",
      tell: "the eyes hold.",
      out: "the eyes close, and the verge is only scrub.",
      next: "the eyes are open. they were never shut." },
  ],
  10: [
    { name: "halim", fig: "imra", them: "him",
      in: "halim the herald announces every walker to an empty chair. he will announce you too.",
      tell: "halim clears his throat.",
      out: "halim announces your passing, to no one in particular.",
      next: "back again. halim remembers the name." },
    { name: "sura", fig: "tesh", them: "her",
      in: "sura fills a cup nobody drinks. it has never once spilled.",
      tell: "sura steadies the cup.",
      out: "sura pours one out for you.",
      next: "the cup was already full when you came back." },
    { name: "benna", fig: "sef", them: "him",
      in: "benna carries the standard furled. it opens for the king alone.",
      tell: "benna grips the pole.",
      out: "benna dips the standard an inch. an honor.",
      next: "the standard is still furled. benna still carries it." },
    { name: "okka", fig: "ruen", them: "him",
      in: "okka keeps the hall's one door. the roof left; the door stayed.",
      tell: "okka leans on the door.",
      out: "okka opens the door the rest of the way.",
      next: "okka watched you come up the stair." },
    { name: "meret", fig: "odel", them: "her",
      in: "meret writes the minutes of a court that never sits. tonight's entry is you.",
      tell: "meret makes a note.",
      out: "meret records the result without comment.",
      next: "meret found your old page." },
    { name: "kasran", fig: "brann", them: "him",
      in: "kasran claims the throne nightly. he has never once sat down.",
      tell: "kasran glances at the seat.",
      out: "kasran bows, which surprises everyone.",
      next: "kasran is still not king." },
    { name: "reya", fig: "mave", them: "her",
      in: "reya rules in no one's name.",
      tell: "reya says nothing.",
      out: "reya signs your pass without reading it.",
      next: "reya remembers exactly how you play." },
    { name: "the throne-warden", fig: "the quiet one", them: "them",
      in: "the throne-warden has dusted an empty chair longer than anyone has been alive.",
      tell: "the warden straightens the seat.",
      out: "the warden steps aside from the dais.",
      next: "the chair is clean. the warden is waiting." },
  ],
  11: [
    { name: "yann", fig: "imra", them: "him",
      in: "yann is lying flat in the grass with his hands behind his head, and has been since the afternoon, and calls it a walk.",
      tell: "yann lifts his head above the grass.",
      out: "yann lies back down. the road is yours.",
      next: "yann's hat is just visible over the grass." },
    { name: "brisa", fig: "sef", them: "her",
      in: "brisa is somewhere in the grass to your left, humming. she will not say where, and does not need to.",
      tell: "the humming stops, then starts again.",
      out: "the humming moves off ahead of you.",
      next: "brisa is humming, somewhere." },
    { name: "hollin", fig: "odel", them: "him",
      in: "hollin cuts a path through the grass with a hook and has cut this one so many times he could do it asleep, and possibly is.",
      tell: "hollin's hook swings once.",
      out: "hollin steps into the grass and the path is yours.",
      next: "hollin is ahead, cutting." },
    { name: "ottilie", fig: "tesh", them: "her",
      in: "ottilie lost a ring in this grass twenty years ago and comes back every summer to not look for it.",
      tell: "ottilie parts the grass with one hand.",
      out: "ottilie straightens up and steps aside.",
      next: "ottilie is bent over the grass." },
    { name: "pike", fig: "ruen", them: "him",
      in: "pike is a boy up to his shoulders in grass, moving in a straight line because he cannot see over it and does not want to.",
      tell: "the grass parts where pike is.",
      out: "pike bursts out onto the road and runs on.",
      next: "pike is in there somewhere." },
    { name: "renn", fig: "brann", them: "him",
      in: "renn ties grass-heads into knots to mark the way and has never once needed them.",
      tell: "renn ties another knot.",
      out: "renn points down the road with a knotted stalk.",
      next: "renn's knots are fresh." },
    { name: "the hunter", fig: "mave", them: "her",
      in: "the hunter has walked this grass every night for a stag she has seen once and never raised the bow to.",
      tell: "the hunter's hand rests on the bow.",
      out: "the hunter lowers the bow she never raised, and lets you by.",
      next: "the hunter is in the grass, still." },
    { name: "the one lying still", fig: "the quiet one", them: "them",
      in: "the one lying still is somewhere close and you cannot see them, and they can see you.",
      tell: "nothing moves in the grass.",
      out: "the grass moves once, and you are past.",
      next: "still." },
  ],
  12: [
    { name: "nael", fig: "imra", them: "him",
      in: "nael keeps the great vane's pivot oiled. it has never once stuck.",
      tell: "nael gives the pivot a turn.",
      out: "nael lets the vane swing your way.",
      next: "back again. nael oiled it for you." },
    { name: "vesh", fig: "sef", them: "him",
      in: "vesh rings the bell of the change, and never one hour early.",
      tell: "vesh's hand goes to the rope.",
      out: "vesh rings it. that one was yours.",
      next: "vesh counted the hours since the last change." },
    { name: "thea", fig: "odel", them: "her",
      in: "thea keeps the almanac with her thumb in this week. the heat ends on a date, not a whim.",
      tell: "thea marks the page.",
      out: "thea writes you into the year.",
      next: "thea found your entry from last time." },
    { name: "sabi", fig: "tesh", them: "her",
      in: "sabi flies a kite on a line long enough to read air nobody can feel.",
      tell: "sabi lets out more line.",
      out: "sabi reels in, and lets you past.",
      next: "sabi kept your line coiled." },
    { name: "orun", fig: "ruen", them: "him",
      in: "orun reads smoke off a slow taper. the smoke has started leaning the other way.",
      tell: "orun shields the taper.",
      out: "orun watches the smoke go your way.",
      next: "orun remembers which way you leaned." },
    { name: "duna", fig: "brann", them: "her",
      in: "duna is already turning the flock. she turned before the vanes did and dares you to say she guessed.",
      tell: "duna whistles the flock round.",
      out: "duna turns the flock past you.",
      next: "duna turned early last time too. she was right then as well." },
    { name: "kip", fig: "mave", them: "him",
      in: "kip tastes the air off his palm, and says nothing useful.",
      tell: "kip wets his palm again.",
      out: "kip shrugs: cooler now.",
      next: "kip has tasted your air before." },
    { name: "the weather-watch", fig: "the quiet one", them: "them",
      in: "the weather-watch has read this hill since before the vanes were planted, and watches the ground instead of the sky.",
      tell: "the weather-watch keeps looking down.",
      out: "the weather-watch steps off the summit stone.",
      next: "the dust never settled. the weather-watch was still watching it." },
  ],
  13: [
    { name: "orrin", fig: "imra", them: "him",
      in: "orrin is the wheelwright. the mallet rides his shoulder between strokes and he has not put it down in thirty years.",
      tell: "orrin lifts the mallet.",
      out: "orrin sets the mallet on the bench, head down. you pass.",
      next: "orrin's mallet is already up." },
    { name: "tamsa", fig: "sef", them: "her",
      in: "tamsa shaves the spokes with a drawknife pulled toward her chest. the curl comes off in one piece or she starts over.",
      tell: "tamsa pulls another curl.",
      out: "tamsa blows the shavings off the bench and lets you by.",
      next: "tamsa has a spoke in the vice for you." },
    { name: "dun", fig: "odel", them: "him",
      in: "dun bends the felloes, the wheel's rim, over steam. he says wood remembers a bend the way a hand remembers a grip.",
      tell: "dun leans on the bend.",
      out: "dun lets the bend spring a little, and steps back.",
      next: "dun's steam is up already." },
    { name: "ilka", fig: "tesh", them: "her",
      in: "ilka is the tyre-smith. the iron hoop goes on red and shrinks cold, and the wheel is a wheel from then on.",
      tell: "ilka turns the hoop in the tongs.",
      out: "ilka quenches the hoop. the hiss is for you.",
      next: "ilka's hoop is glowing again." },
    { name: "pem", fig: "ruen", them: "him",
      in: "pem is the apprentice and holds the lamp, and holds it wherever he is looking, which is not where the work is.",
      tell: "pem swings the lamp round.",
      out: "pem holds the lamp on the door for you, and gets it right.",
      next: "pem has the lamp up. it is pointed at you." },
    { name: "varo", fig: "brann", them: "her",
      in: "varo turns the axles on the pole-lathe, one foot on the treadle. a true axle rolls off the bench in a straight line and stops.",
      tell: "varo's foot comes down on the treadle.",
      out: "varo lifts her foot. the lathe runs down.",
      next: "varo's lathe is turning." },
    { name: "the master", fig: "mave", them: "her",
      in: "the master measures every gap with the span of one hand and is never wrong.",
      tell: "the master's hand opens to a span.",
      out: "the master closes the hand, and nods once.",
      next: "the master is measuring you." },
    { name: "the crossbar-hand", fig: "the quiet one", them: "them",
      in: "the crossbar-hand keeps both palms flat on the vice's beam and has not spoken since the beam went in.",
      tell: "the crossbar-hand does not move.",
      out: "the crossbar-hand lifts one palm.",
      next: "both palms are on the beam." },
  ],
  14: [
    { name: "ozan", fig: "imra", them: "him",
      in: "ozan keeps the tally: every dull stone in the hall has a line in his book and not one of them has a name.",
      tell: "ozan makes another mark.",
      out: "ozan closes the book. one line short, and he lets it go.",
      next: "ozan has your line ready." },
    { name: "mirel", fig: "sef", them: "her",
      in: "mirel weighs. the scales are true, and every stone weighs what it weighs, which is never what it looks.",
      tell: "mirel adds a weight.",
      out: "mirel lifts her hand off the pan and the beam settles your way.",
      next: "mirel's pans are level, waiting." },
    { name: "sefir", fig: "odel", them: "him",
      in: "sefir holds the keys. there are more keys than doors, and he has never said which is which.",
      tell: "sefir turns a key over.",
      out: "sefir unlocks one door, and does not say which.",
      next: "sefir has the key out already." },
    { name: "tunn", fig: "tesh", them: "him",
      in: "tunn trims the lamps, all of them, every night, and lights none: the hall has one light and it is not a lamp.",
      tell: "tunn trims a wick.",
      out: "tunn sets the trimmer down in the dark.",
      next: "tunn is at the lamps, still unlit." },
    { name: "roka", fig: "ruen", them: "her",
      in: "roka polishes the stones that will never shine, one a night, for as long as anyone remembers.",
      tell: "roka breathes on a stone and rubs it.",
      out: "roka puts the cloth away. the stone is as dull as before.",
      next: "roka has a stone in her hand." },
    { name: "esen", fig: "brann", them: "him",
      in: "esen appraises through a glass and has yet to find a flaw in anything in this hall, because nothing here has a face to hold one.",
      tell: "esen raises the glass.",
      out: "esen lowers the glass and says nothing about you.",
      next: "esen has the glass up." },
    { name: "the treasurer", fig: "mave", them: "her",
      in: "the treasurer counts the whole hall every night and arrives at the same number.",
      tell: "the treasurer's count does not pause.",
      out: "the treasurer stops counting, and nods you through.",
      next: "the treasurer is counting you." },
    { name: "the duster", fig: "the quiet one", them: "them",
      in: "the duster keeps one jewel clean and has never touched another stone in the hall.",
      tell: "the duster's cloth passes over the jewel.",
      out: "the duster steps back from the light.",
      next: "the duster is at the jewel." },
  ],
  15: [
    { name: "hala", fig: "imra", them: "her",
      in: "hala dyes. her hands are stained to the wrist and her sleeves are down over them, and the colour of tonight's vat is nobody's business.",
      tell: "hala pulls her sleeve down.",
      out: "hala pushes both sleeves up. indigo, to the elbow. she does not mind you seeing now.",
      next: "hala's sleeves are down again." },
    { name: "merin", fig: "sef", them: "her",
      in: "merin folds. the stack beside her is taller than she is, every fold the same width, and what is in the middle of it has not been seen since it went in.",
      tell: "merin smooths a fold.",
      out: "merin lifts the top of the stack an inch and lets you look. cloth, all the way down.",
      next: "merin is folding. the stack is taller." },
    { name: "tobiah", fig: "odel", them: "him",
      in: "tobiah hangs the lines. he keeps the pegs in his mouth, which is why he says nothing, which is also why they gave him the lines.",
      tell: "tobiah takes a peg from his mouth.",
      out: "tobiah unpegs one sheet and lets it down. behind it, the road.",
      next: "tobiah has a mouthful of pegs." },
    { name: "senna", fig: "tesh", them: "her",
      in: "senna mends. there is a tear in the great cloth that nobody else has noticed, and she has been at it for three nights, and nobody will ever notice that either.",
      tell: "senna bites a thread.",
      out: "senna holds the mended place up to arcturus. you cannot find it. good.",
      next: "senna is mending. the same place." },
    { name: "ilke", fig: "ruen", them: "her",
      in: "ilke carries the bride's cloth. she has carried it three years, folded, and has never seen the bride, and has never asked.",
      tell: "ilke shifts the bundle.",
      out: "ilke sets the bundle down on the road, and does not unfold it, and steps back.",
      next: "ilke has the bundle. still folded." },
    { name: "oran", fig: "brann", them: "him",
      in: "oran keeps the vat. the lid is on. it has been on all night and it will be on in the morning, and the dye keeps better for it.",
      tell: "oran rests a hand on the lid.",
      out: "oran lifts the lid one finger's width. steam, and a colour you did not expect.",
      next: "oran's hand is on the lid." },
    { name: "the seamstress", fig: "mave", them: "her",
      in: "the seamstress has a needle and no thread you can see.",
      tell: "the seamstress does not look up from the needle.",
      out: "the seamstress ties off, and there was thread after all, the colour of the cloth.",
      next: "the seamstress has the needle. no thread showing." },
    { name: "the covered one", fig: "the quiet one", them: "them",
      in: "the covered one stands under a sheet. all of them. nobody has said who it is, and",
      tell: "the sheet does not move.",
      out: "the covered one steps aside, still covered, and the hem lifts an inch off the road.",
      next: "the covered one is standing there. under it." },
  ],
  16: [
    { name: "odri", fig: "imra", them: "her",
      in: "odri is the weigh-master and owns a set of brass weights, polished, none of which has been in a pan since she was given them.",
      tell: "odri sets a weight down, and picks it up.",
      out: "odri puts the weights away, and the square is yours.",
      next: "odri has the weights out." },
    { name: "pol", fig: "sef", them: "him",
      in: "pol checks the merchants' scales against the great one every market day and has never once found a true pair.",
      tell: "pol tilts a small scale and watches it settle.",
      out: "pol marks a scale true, for once, and steps back.",
      next: "pol has a scale in each hand." },
    { name: "senga", fig: "odel", them: "her",
      in: "senga sells by the handful and refuses the balance on principle. her handfuls are, as it happens, exactly equal.",
      tell: "senga holds out two handfuls.",
      out: "senga tips both hands into your bag.",
      next: "senga's hands are full." },
    { name: "kade", fig: "tesh", them: "him",
      in: "kade carries the sacks and knows the weight of each by the shoulder it sits on, to the ounce, and has never needed the pan.",
      tell: "kade shifts the sack to the other shoulder.",
      out: "kade sets the sack down at the frame's foot.",
      next: "kade is under a sack." },
    { name: "imke", fig: "ruen", them: "her",
      in: "imke is the assayer and tests gold by rubbing it beside a known streak on a black stone. two things side by side, and the eye decides.",
      tell: "imke draws a streak.",
      out: "imke holds the stone up to the lamp, and nods.",
      next: "imke has the touchstone out." },
    { name: "ruf", fig: "brann", them: "him",
      in: "ruf oils the chains so the beam swings free, and says a balance that sticks is a balance that lies.",
      tell: "ruf works oil into a link.",
      out: "ruf gives the beam a push and lets it swing you through.",
      next: "ruf is at the chains." },
    { name: "the arbiter", fig: "mave", them: "her",
      in: "the arbiter settles disputes by standing between two people until they agree.",
      tell: "the arbiter does not move from between.",
      out: "the arbiter steps out from between, and the way is clear.",
      next: "the arbiter is standing between." },
    { name: "the one in the other pan", fig: "the quiet one", them: "them",
      in: "the one in the other pan sits in the empty pan of the great balance, and it stays exactly level, which nobody can explain.",
      tell: "the empty pan does not move.",
      out: "the one in the other pan steps out, and the beam swings.",
      next: "still level." },
  ],
  17: [
    { name: "ardith", fig: "imra", them: "her",
      in: "ardith is the wall-warden and carries the keys on a ring. no gate on this wall has been unlocked in her lifetime, and the keys are polished anyway.",
      tell: "ardith's keys ring once.",
      out: "ardith takes one key off the ring and holds it out.",
      next: "ardith has the key out already." },
    { name: "temmin", fig: "sef", them: "him",
      in: "temmin lights the torches along the walk each night with a taper, one at a time, and puts none of them out.",
      tell: "temmin lights the next torch.",
      out: "temmin lights your way to the keep.",
      next: "temmin's taper is lit." },
    { name: "sol", fig: "odel", them: "him",
      in: "sol is the sentry and looks out, never in. in all his watches nothing has come within an arrow's flight and he has not stopped looking.",
      tell: "sol raises the lantern.",
      out: "sol turns round, for once, and lets you pass behind him.",
      next: "sol's lantern is up." },
    { name: "brannoc", fig: "tesh", them: "him",
      in: "brannoc the mason repoints stones that have not shifted a hair. he says a wall is kept, not built.",
      tell: "brannoc taps a stone with the trowel.",
      out: "brannoc sets the trowel down on the parapet.",
      next: "brannoc is at the stones." },
    { name: "ives", fig: "ruen", them: "him",
      in: "ives carries water up from the keep's well, which has never once run dry, in the same two buckets.",
      tell: "ives sets the buckets down.",
      out: "ives offers you the dipper.",
      next: "ives is halfway up with the buckets." },
    { name: "lune", fig: "brann", them: "her",
      in: "lune is the archer and her bow is unstrung. nothing has come in range in a hundred years and she is at her post every night regardless.",
      tell: "lune touches the bowstring in her belt.",
      out: "lune steps aside from the loophole.",
      next: "lune is at the loophole." },
    { name: "the castellan", fig: "mave", them: "her",
      in: "the castellan holds the keep's one key and has never needed it.",
      tell: "the castellan's hand closes on the key.",
      out: "the castellan opens the hand.",
      next: "the castellan is at the keep door." },
    { name: "the gate-hand", fig: "the quiet one", them: "them",
      in: "the gate-hand stands with one hand on the portcullis chain, and has stood there since the chain was hung.",
      tell: "the gate-hand's grip tightens.",
      out: "the gate-hand lets the chain run.",
      next: "the hand is on the chain." },
  ],
  18: [
    { name: "asha", fig: "imra", them: "her",
      in: "asha feeds the kiln before she fights.",
      tell: "asha stokes it higher.",
      out: "asha banks the fire. the road goes on.",
      next: "back again. asha kept the kiln hot for you." },
    { name: "derev", fig: "sef", them: "him",
      in: "derev counts embers, not cards.",
      tell: "derev counts again, slower.",
      out: "derev nods at the ground you kept.",
      next: "derev remembers your count. it was short then." },
    { name: "onna", fig: "odel", them: "her",
      in: "onna waits the way the sting waits.",
      tell: "onna stops waiting.",
      out: "onna: you reached, and it held.",
      next: "onna turned you back once. she waits the same way." },
    { name: "kel", fig: "tesh", them: "him",
      in: "kel keeps the rain off his corners.",
      tell: "kel gives up a corner.",
      out: "kel trades you the night.",
      next: "kel kept the corners dry last time too." },
    { name: "sorev", fig: "ruen", them: "him",
      in: "sorev reads heat the way others read hands.",
      tell: "sorev misread that one.",
      out: "sorev reads your walk back with respect.",
      next: "sorev read you once already. the heat says you changed." },
    { name: "brakka", fig: "brann", them: "her",
      in: "brakka answers red with red.",
      tell: "brakka found the fight she wanted.",
      out: "brakka wanted this fight. you ended it.",
      next: "brakka remembers the fight. she wants it again." },
    { name: "immi", fig: "mave", them: "her",
      in: "immi gives the fire nothing to eat.",
      tell: "immi gave that one away.",
      out: "immi gives you this one, once.",
      next: "immi starved you out before. nothing has changed." },
    { name: "the rain-keeper", fig: "the quiet one", them: "them",
      in: "the rain-keeper has tended this road since the first rains broke.",
      tell: "the rain-keeper says nothing.",
      out: "the rain-keeper steps aside.",
      next: "the rains have broken here before. the rain-keeper remembers." },
  ],
  19: [
    { name: "muza", fig: "imra", them: "her",
      in: "muza runs the cut. she chalked tonight's edge before you got here, and the line does not move.",
      tell: "muza checks her line.",
      out: "muza steps back off the edge.",
      next: "muza kept your line chalked." },
    { name: "hev", fig: "sef", them: "him",
      in: "hev shores whatever the digging opens. nothing has come down on anyone yet.",
      tell: "hev sets another prop.",
      out: "hev takes a prop out and lets you through.",
      next: "hev's props are still standing where you left them." },
    { name: "ansu", fig: "odel", them: "her",
      in: "ansu sifts every basket. what is worth keeping was never the big pieces.",
      tell: "ansu shakes the sieve.",
      out: "ansu passes your basket through unsifted.",
      next: "ansu still has what she sifted out of your last one." },
    { name: "kori", fig: "tesh", them: "him",
      in: "kori carries spoil up and empty baskets down, all night, and has never been asked twice.",
      tell: "kori swings the basket up.",
      out: "kori sets the basket down and lets you by.",
      next: "kori remembers the weight of your last load." },
    { name: "zayn", fig: "ruen", them: "him",
      in: "zayn cuts the roots that grew down into the grave. they take longer to get through than the stone did.",
      tell: "zayn tests the blade.",
      out: "zayn cuts you a way through.",
      next: "zayn's cuts from last time have healed over." },
    { name: "orsa", fig: "brann", them: "her",
      in: "orsa tallies what comes out. she has the whole burial written down twice, in case.",
      tell: "orsa makes a mark.",
      out: "orsa writes the loss down as yours.",
      next: "orsa found your tally from before." },
    { name: "veya", fig: "mave", them: "her",
      in: "veya came with the bones and will walk behind them to the new ground.",
      tell: "veya folds the cloth again.",
      out: "veya lets the road pass first.",
      next: "veya has carried this cloth past you before." },
    { name: "the ground-watch", fig: "the quiet one", them: "them",
      in: "the ground-watch keeps a palm flat on the cut face and feels for movement.",
      tell: "the ground-watch presses the wall.",
      out: "the ground-watch takes the hand off the wall.",
      next: "nothing has shifted since. the ground-watch would know." },
  ],
  20: [
    { name: "merit", fig: "imra", them: "her",
      in: "merit is going down with the jars empty, one on each hip, and does not hurry because the river is not going anywhere.",
      tell: "merit shifts a jar.",
      out: "merit steps off the path to let you down first.",
      next: "merit is going down." },
    { name: "oba", fig: "sef", them: "him",
      in: "oba is coming back with the jars full and walks slower for it, and is glad of the excuse.",
      tell: "oba steadies the jars.",
      out: "oba steps off the path and lets you by, jars and all.",
      next: "oba is coming back." },
    { name: "tesfa", fig: "odel", them: "him",
      in: "tesfa is the herd-boy driving the birds down to the water with a switch he has never once had to use.",
      tell: "tesfa flicks the switch at nothing.",
      out: "tesfa waves you down ahead of the birds.",
      next: "tesfa is driving them down." },
    { name: "nuru", fig: "tesh", them: "her",
      in: "nuru is the herd-girl bringing the birds back with nothing but her voice, and they come.",
      tell: "nuru calls once.",
      out: "nuru calls the birds off the path for you.",
      next: "nuru is bringing them back." },
    { name: "kito", fig: "ruen", them: "him",
      in: "kito goes down to the river every night and has never been seen to come back, and is here every night, going down.",
      tell: "kito keeps going down.",
      out: "kito goes on down, and you follow.",
      next: "kito is going down again." },
    { name: "dalia", fig: "brann", them: "her",
      in: "dalia is only ever coming back, and nobody saw her go down, and she does not say what she was doing at the water.",
      tell: "dalia looks back at the river once.",
      out: "dalia stands aside on her way back.",
      next: "dalia is coming back." },
    { name: "the drover", fig: "mave", them: "her",
      in: "the drover stands where the two files pass and lets neither through first.",
      tell: "the drover holds up a hand and both files stop.",
      out: "the drover drops the hand, and both files move, and so do you.",
      next: "the drover is standing between the files." },
    { name: "the one on the bank", fig: "the quiet one", them: "them",
      in: "the one on the bank sits at the water's edge facing the river and has neither gone down nor come back.",
      tell: "the one on the bank does not turn.",
      out: "the one on the bank moves over on the bank, and there is room.",
      next: "still on the bank." },
  ],
  21: [
    { name: "daru", fig: "imra", them: "her",
      in: "daru walks the night watch with a lantern she stopped filling.",
      tell: "daru swings the dark lantern.",
      out: "daru waves you through her quarter.",
      next: "back again. daru knows your step by now." },
    { name: "nesh", fig: "sef", them: "him",
      in: "nesh cried the hour here for thirty years. the bell is wrapped in cloth now.",
      tell: "nesh almost calls it.",
      out: "nesh unwraps the bell an inch, and doesn't ring it.",
      next: "nesh counted the hours you were gone." },
    { name: "olm", fig: "tesh", them: "him",
      in: "olm carries the lighting-pole past hooks with nothing on them, every night, in order.",
      tell: "olm lifts the pole anyway.",
      out: "olm skips a hook for you.",
      next: "olm kept your street on the round." },
    { name: "tavi", fig: "odel", them: "her",
      in: "tavi chalks the doors. she will not say what the marks mean.",
      tell: "tavi marks that too.",
      out: "tavi rubs one mark out.",
      next: "your door is still marked, tavi says." },
    { name: "ren", fig: "ruen", them: "her",
      in: "ren mends shutters that are latched from the inside. someone latched them.",
      tell: "ren tightens a hinge.",
      out: "ren leaves one shutter open behind you.",
      next: "ren fixed what you rattled last time." },
    { name: "sabb", fig: "brann", them: "him",
      in: "sabb sweeps a street nobody walks and dares you to say it is pointless.",
      tell: "sabb sweeps that off his stones.",
      out: "sabb sweeps a clean line to the square.",
      next: "sabb swept your dust out once already." },
    { name: "iyad", fig: "mave", them: "him",
      in: "iyad the bailiff carries a writ nobody will accept.",
      tell: "iyad notes it on the writ.",
      out: "iyad rolls the writ up. not tonight.",
      next: "iyad still has your name on the paper." },
    { name: "the last tenant", fig: "the quiet one", them: "her",
      in: "the last tenant stands in her doorway holding a key she has not used since the quarter emptied.",
      tell: "the last tenant says nothing at all.",
      out: "the last tenant steps back inside.",
      next: "the door never opened. she was still standing there." },
  ],
  23: [
    { name: "sema", fig: "imra", them: "her",
      in: "sema keeps the beat with her knuckles on the rail. the drums are asleep; she isn't.",
      tell: "sema raps the rail twice.",
      out: "sema lets the rail rest. the road goes on.",
      next: "back again. sema never dropped the count." },
    { name: "odu", fig: "sef", them: "him",
      in: "odu sweeps under bells that no longer ring, and counts the dust.",
      tell: "odu sweeps that away.",
      out: "odu nods, and sweeps your path clear.",
      next: "odu swept your old footprints out once. here they are again." },
    { name: "lien", fig: "tesh", them: "her",
      in: "lien lights the galleries one flame a night. tonight she lights them for you.",
      tell: "lien shields the flame.",
      out: "lien leaves a lamp lit behind you.",
      next: "lien remembers which lamps you passed." },
    { name: "pava", fig: "ruen", them: "him",
      in: "pava hauls the great drum's hoist rope. he has never heard it struck.",
      tell: "pava takes another grip.",
      out: "pava lets the rope out a little. up you go.",
      next: "pava has hauled since you left. the rope is shorter." },
    { name: "meki", fig: "odel", them: "her",
      in: "meki counts the echoes of strikes nobody living struck.",
      tell: "meki adds one to the count.",
      out: "meki counts you going up.",
      next: "your echo never left this tower, meki says." },
    { name: "doran", fig: "brann", them: "him",
      in: "doran the drummer is deaf, and reads your game through the floor.",
      tell: "doran feels that one land.",
      out: "doran lays his palm flat: he felt you win.",
      next: "doran knows your footsteps now." },
    { name: "sorn", fig: "mave", them: "her",
      in: "sorn calls no curfew anymore.",
      tell: "sorn says nothing of it.",
      out: "sorn waives the curfew, once.",
      next: "sorn remembers exactly when you left." },
    { name: "the tower-heart", fig: "the quiet one", them: "her",
      in: "the tower-heart has stood under the great drum so long her pulse keeps the hour.",
      tell: "the tower-heart misses no beat.",
      out: "the tower-heart steps from under the skin.",
      next: "the hour never stopped. the tower-heart kept it for you." },
  ],
  24: [
    { name: "nefa", fig: "imra", them: "her",
      in: "nefa cuts the ice, where there is ice. tonight there is nothing to cut and she is standing with the saw down, and does not seem to mind.",
      tell: "nefa lowers the saw.",
      out: "nefa sets the saw on nothing, and it stays.",
      next: "nefa is standing there. saw down." },
    { name: "brann", fig: "sef", them: "him",
      in: "brann fishes. through the ice, when there is ice; tonight through nothing at all. he has caught nothing and is not surprised.",
      tell: "brann lets the line out.",
      out: "brann draws the line up. empty. good.",
      next: "brann is fishing nothing." },
    { name: "oda", fig: "odel", them: "her",
      in: "oda draws the blood off. the jar is at her hip and it is empty, which is how a physician likes a jar.",
      tell: "oda taps the empty jar.",
      out: "oda turns the jar over. nothing falls.",
      next: "oda has the jar. empty." },
    { name: "tam", fig: "tesh", them: "him",
      in: "tam sets bones. nothing is broken here. he is holding the splints anyway, because a physician who puts them down is not a physician.",
      tell: "tam shifts the splints.",
      out: "tam lays the splints on the dark and steps over them.",
      next: "tam has the splints. nothing broken." },
    { name: "hesh", fig: "ruen", them: "him",
      in: "hesh carries water. two pails on a yoke, both empty, both light, and he walks as if they were full.",
      tell: "hesh eases the yoke.",
      out: "hesh sets the pails down, and they do not ring, because there is nothing in them.",
      next: "hesh has the yoke. light." },
    { name: "sil", fig: "brann", them: "her",
      in: "sil bleeds the fever out. there is no fever. she has let everything go that could be let go, and it went.",
      tell: "sil opens one hand.",
      out: "sil opens both hands. empty. that is the cure.",
      next: "sil is here. hands open." },
    { name: "the old physician", fig: "mave", them: "her",
      in: "the old physician's bag is closed. there is nothing left in it to give and nothing left out here to give it to.",
      tell: "the old physician does not open the bag.",
      out: "the old physician opens the bag and shows you: nothing. it was always nothing.",
      next: "the old physician's bag is closed." },
    { name: "the hundredth", fig: "the quiet one", them: "them",
      in: "the hundredth physician is the one who healed by leaving. you cannot quite see them.",
      tell: "nothing moves.",
      out: "nothing moves, and the way is open.",
      next: "nothing is there. it is waiting." },
  ],
  25: [
    { name: "naila", fig: "imra", them: "her",
      in: "naila keeps a name that was never written down.",
      tell: "naila writes nothing down.",
      out: "naila keeps your name now, with the other one.",
      next: "back again. naila never forgot your name." },
    { name: "veth", fig: "sef", them: "him",
      in: "veth counts what the camp buried, and where.",
      tell: "veth adds it to the count.",
      out: "veth marks your win where no one will find it.",
      next: "veth dug up your record. it was thin." },
    { name: "orna", fig: "odel", them: "her",
      in: "orna guards a grave with no stone on it.",
      tell: "orna stands a little closer to it.",
      out: "orna: the grave keeps. so do you.",
      next: "orna turned you back once, and told no one." },
    { name: "pell", fig: "tesh", them: "him",
      in: "pell holds a debt nobody living can collect.",
      tell: "pell calls a little of it in.",
      out: "pell strikes your night off the ledger.",
      next: "pell knows what you owe from last time." },
    { name: "sarai", fig: "ruen", them: "her",
      in: "sarai keeps a letter she has never opened.",
      tell: "sarai turns the letter over.",
      out: "sarai: some things are better handed on.",
      next: "sarai read your game the way she won't read the letter." },
    { name: "dov", fig: "brann", them: "him",
      in: "dov guards the way in, which is also the way out.",
      tell: "dov closes the way behind him.",
      out: "dov steps out of the doorway.",
      next: "dov barred this way to you before." },
    { name: "lys", fig: "mave", them: "her",
      in: "lys shows you seven tents. she sleeps in the eighth.",
      tell: "lys moves her bed again.",
      out: "lys leaves the eighth tent unlit for you.",
      next: "lys counted you out once. the eighth tent has moved." },
    { name: "the lamp-keeper", fig: "the quiet one", them: "them",
      in: "the lamp-keeper trims the one lit wick, and has kept every secret the camp ever gave.",
      tell: "the lamp-keeper shields the flame.",
      out: "the lamp-keeper opens the flap.",
      next: "the light went out for you once. the lamp-keeper relit it." },
  ],
  26: [
    { name: "tamir", fig: "imra", them: "him",
      in: "tamir keeps the gate. your quarter's token goes in his box as you pass, and comes back when you leave, not before.",
      tell: "tamir sets the token down.",
      out: "tamir hands your token back early.",
      next: "tamir still had your token from last time." },
    { name: "nasha", fig: "sef", them: "her",
      in: "nasha keeps the hearth alight all night, because the cot is cold and the room should not be.",
      tell: "nasha turns a log.",
      out: "nasha banks the fire for you.",
      next: "nasha kept your place by the fire." },
    { name: "vell", fig: "odel", them: "him",
      in: "vell carries water up from the fore spout. the jar pours whether anyone is lodged here or not.",
      tell: "vell sets the jar down.",
      out: "vell pours for you first.",
      next: "vell remembers how you take it." },
    { name: "sadir", fig: "tesh", them: "him",
      in: "sadir mends saddles by lamplight, and every guest's saddle hangs in the bay they slept in. markab is the saddle; this house is named for it.",
      tell: "sadir pulls the girth tight.",
      out: "sadir hangs your saddle in the good bay.",
      next: "sadir kept your saddle oiled." },
    { name: "ennu", fig: "ruen", them: "her",
      in: "ennu cooks for whoever is in, and tonight there is one plate more than there are mouths.",
      tell: "ennu stirs the pot.",
      out: "ennu puts a plate aside for you.",
      next: "ennu knows what you left last time." },
    { name: "borin", fig: "brann", them: "him",
      in: "borin walks the hall gate to gate all night and dares it to bring him something.",
      tell: "borin turns at the wall.",
      out: "borin steps out of your way.",
      next: "borin has walked past you before." },
    { name: "raqi", fig: "mave", them: "her",
      in: "raqi keeps the book of guests. she has your name from last time.",
      tell: "raqi turns a page.",
      out: "raqi writes you out clean.",
      next: "raqi found your entry and did not read it aloud." },
    { name: "the house-watch", fig: "the quiet one", them: "her",
      in: "the house-watch sits where she can see both gates and the cot between them.",
      tell: "the house-watch does not look up.",
      out: "the house-watch lets you by.",
      next: "the house-watch has not moved. the cot is where it was." },
  ],
  27: [
    { name: "teru", fig: "imra", them: "her",
      in: "teru sets back every stone the water lifts. she has done it every season and the line is still straight.",
      tell: "teru taps a stone home.",
      out: "teru leaves the stone where it fell.",
      next: "teru remembers which stones you loosened." },
    { name: "isha", fig: "odel", them: "her",
      in: "isha sounds the depth beside the crossing. she can tell you the number before the pole is wet.",
      tell: "isha reads the pole.",
      out: "isha lets the pole rest.",
      next: "isha has your depth written down from last time." },
    { name: "malek", fig: "tesh", them: "him",
      in: "malek carries fill up to the crown all night, so the crown stays a hand above the water.",
      tell: "malek tips a basket.",
      out: "malek sets the basket down.",
      next: "malek's fill from last time is still holding." },
    { name: "wen", fig: "sef", them: "her",
      in: "wen marks the water's height on a post each night. there are a great many marks and this year's is high.",
      tell: "wen cuts a new mark.",
      out: "wen lets tonight go unmarked.",
      next: "wen found your mark under this one." },
    { name: "sabra", fig: "ruen", them: "her",
      in: "sabra ferried this crossing before there were stones. her boat is tied up and she would rather it stayed that way.",
      tell: "sabra glances at her boat.",
      out: "sabra unties the boat after all.",
      next: "sabra's boat has not moved since you came through." },
    { name: "corvin", fig: "brann", them: "him",
      in: "corvin opens the culverts so the flood goes under the road instead of over it. it has never once gone over.",
      tell: "corvin hauls a gate open.",
      out: "corvin lets a gate stand shut.",
      next: "corvin's gates are open where you left them." },
    { name: "dala", fig: "mave", them: "her",
      in: "dala walks the stones at night with the lantern held low, reading the surface.",
      tell: "dala lowers the lantern.",
      out: "dala steps aside on the narrow part.",
      next: "dala has walked behind you before." },
    { name: "the water-watch", fig: "the quiet one", them: "them",
      in: "the water-watch stands at the middle of the crossing and does not look away from the surface.",
      tell: "the water-watch keeps looking.",
      out: "the water-watch turns from the water.",
      next: "nothing has surfaced since. the water-watch would know." },
  ],
  28: [
    { name: "hara", fig: "imra", them: "her",
      in: "hara turns the windlass. she has never once asked what is on the rope.",
      tell: "hara takes another turn.",
      out: "hara lets the handle rest. up you go.",
      next: "back again. hara's arms remember." },
    { name: "tovi", fig: "sef", them: "him",
      in: "tovi drops a stone and counts. that is how deep you still are.",
      tell: "tovi counts again, lower.",
      out: "tovi calls your depth: shallow now.",
      next: "tovi has counted you before. you were further down." },
    { name: "esk", fig: "odel", them: "him",
      in: "esk mends buckets. nothing he has patched has ever come up empty.",
      tell: "esk patches that.",
      out: "esk hands you a whole bucket.",
      next: "esk kept your bucket. it needed work." },
    { name: "nira", fig: "tesh", them: "her",
      in: "nira finds water with a bent rod and no explanation.",
      tell: "nira's rod dips.",
      out: "nira points you up instead of down.",
      next: "nira found you once already." },
    { name: "bel", fig: "ruen", them: "him",
      in: "bel inspects the rope hand over hand, and knows every splice by feel.",
      tell: "bel finds a thin place.",
      out: "bel says the rope will hold you.",
      next: "bel remembers your weight." },
    { name: "kesh", fig: "brann", them: "him",
      in: "kesh went down once and came back changed. he will not say what he saw.",
      tell: "kesh laughs at the dark.",
      out: "kesh steps aside from the ladder.",
      next: "kesh knows you have seen a little of it now." },
    { name: "aven", fig: "mave", them: "her",
      in: "aven keeps the ladder nobody uses.",
      tell: "aven says nothing about it.",
      out: "aven lowers the ladder anyway.",
      next: "aven kept the rungs clear for you." },
    { name: "the well-watch", fig: "the quiet one", them: "them",
      in: "the well-watch has looked into the mouth for as long as there has been a mouth.",
      tell: "the well-watch does not look away.",
      out: "the well-watch moves from the rim.",
      next: "the mouth never closed. the well-watch was still looking." },
  ],
};
